          {
            id: 'g8a-u1-w1',
            word: 'suppose',
            phonetic: '/sa\'pauz/',
            senses: [{ pos: 'v.', meaning: '想,认为' }],
          },
          {
            id: 'g8a-u1-w2',
            word: 'birthmark',
            phonetic: '/bs:θma:k/',
            senses: [{ pos: 'n.', meaning: '胎记，胎痣' }],
          },
          {
            id: 'g8a-u1-w3',
            word: 'strawberry',
            phonetic: '/\'stro:bari/',
            senses: [{ pos: 'n.', meaning: '草莓' }],
          },
          {
            id: 'g8a-u1-w4',
            word: 'away',
            phonetic: '/\'wer/',
            senses: [{ pos: 'adv.', meaning: '朝另一个方向' }],
          },
          {
            id: 'g8a-u1-w5',
            word: 'crowded',
            phonetic: '/kraudid/',
            senses: [{ pos: 'adj.', meaning: '挤满人(物)的;拥挤的' }],
          },
          {
            id: 'g8a-u1-w6',
            word: 'just',
            phonetic: '/d3ast/',
            senses: [{ pos: 'adv.', meaning: '正好，恰好' }],
          },
          {
            id: 'g8a-u1-w7',
            word: 'disaster',
            phonetic: '/dza:ste/',
            senses: [{ pos: 'n.', meaning: '灾难，不幸' }],
          },
          {
            id: 'g8a-u1-w8',
            word: 'therefore',
            phonetic: '/oeaf:/',
            senses: [{ pos: 'adv.', meaning: '因此，由此,所以' }],
          },
          {
            id: 'g8a-u1-w9',
            word: 'cover',
            phonetic: '/kAve/',
            senses: [{ pos: 'v.', meaning: '遮盖' }],
          },
          {
            id: 'g8a-u1-w10',
            word: 'until',
            phonetic: '/An\'til/',
            senses: [{ pos: 'prep.', meaning: '直到......为' }],
          },
          {
            id: 'g8a-u1-w11',
            word: 'instead',
            phonetic: '/in\'sted/',
            senses: [{ pos: 'adv.', meaning: '代替;而不是' }],
          },
          {
            id: 'g8a-u1-w12',
            word: 'instead of',
            senses: [{ pos: '', meaning: '代替......;而不是......' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u1-w13',
            word: 'although',
            phonetic: '/o:l\'dau/',
            senses: [{ pos: 'conj.', meaning: '虽然，尽管' }],
          },
          {
            id: 'g8a-u1-w14',
            word: 'bathroom',
            phonetic: '/ba:0rum/',
            senses: [{ pos: 'n.', meaning: '浴室,卫生间' }],
          },
          {
            id: 'g8a-u1-w15',
            word: 'truly',
            phonetic: '/tru:li/',
            senses: [{ pos: 'adv.', meaning: '真实地，确实地' }],
          },
          {
            id: 'g8a-u1-w16',
            word: 'paint',
            phonetic: '/peint/',
            senses: [{ pos: 'v.', meaning: '(用颜料)画，绘' }],
          },
          {
            id: 'g8a-u1-w17',
            word: 'own',
            phonetic: '/aun/',
            senses: [{ pos: 'adj.', meaning: '自己的，属于自己的' }],
          },
          {
            id: 'g8a-u1-w18',
            word: 'yet',
            phonetic: '/jet/',
            senses: [{ pos: 'adv.', meaning: '(用于否定句)还，尚' }],
          },
          {
            id: 'g8a-u1-w19',
            word: 'anyway',
            phonetic: '/\'eniwei/',
            senses: [{ pos: 'adv.', meaning: '总之' }],
          },
          {
            id: 'g8a-u1-w20',
            word: 'already',
            phonetic: '/o:l\'redi/',
            senses: [{ pos: 'adv.', meaning: '已经' }],
          },
          {
            id: 'g8a-u1-w21',
            word: 'special',
            phonetic: '/\'spejal/',
            senses: [{ pos: 'adj.', meaning: '特殊的，特别的' }],
          },
          {
            id: 'g8a-u1-w22',
            word: 'difference',
            phonetic: '/difarans/',
            senses: [{ pos: 'n.', meaning: '差别，差异' }],
          },
          {
            id: 'g8a-u1-w23',
            word: 'hate',
            phonetic: '/heit/',
            senses: [{ pos: 'v.', meaning: '讨厌，不喜欢' }],
          },
          {
            id: 'g8a-u1-w24',
            word: 'opinion',
            phonetic: '/\'pnjan/',
            senses: [{ pos: 'n.', meaning: '意见，看法，主张' }],
          },
          {
            id: 'g8a-u1-w25',
            word: 'row',
            phonetic: '/rau/',
            senses: [{ pos: 'n.', meaning: '一排，一行' }],
          },
          {
            id: 'g8a-u1-w26',
            word: 'thing',
            phonetic: '/0in/',
            senses: [{ pos: 'n.', meaning: '东西，物' }],
          },
          {
            id: 'g8a-u1-w27',
            word: 'height',
            phonetic: '/hart/',
            senses: [{ pos: 'n.', meaning: '身高;高，高度' }],
          },
          {
            id: 'g8a-u1-w28',
            word: 'friendship',
            phonetic: '/frendjip/',
            senses: [{ pos: 'n.', meaning: '友谊' }],
          },
          {
            id: 'g8a-u1-w29',
            word: 'among',
            phonetic: '/\'mAn/',
            senses: [{ pos: 'prep.', meaning: '在......当中' }],
          },
          {
            id: 'g8a-u1-w30',
            word: 'wizard',
            phonetic: '/\'wized/',
            senses: [{ pos: 'n.', meaning: '男巫' }],
          },
          {
            id: 'g8a-u1-w31',
            word: 'brain',
            phonetic: '/bremn/',
            senses: [{ pos: 'n.', meaning: '脑，大脑' }],
          },
          {
            id: 'g8a-u1-w32',
            word: 'value',
            phonetic: '/valju:/',
            senses: [{ pos: 'n.', meaning: '价值观' }],
          },
          {
            id: 'g8a-u1-w33',
            word: 'quality',
            phonetic: '/\'kwplati/',
            senses: [{ pos: 'n.', meaning: '素质;品德，品性' }],
          },
          {
            id: 'g8a-u1-w34',
            word: 'ourselves',
            phonetic: '/aue\'selvz/',
            senses: [{ pos: 'pron.', meaning: '我们自己' }],
          },
          {
            id: 'g8a-u1-w35',
            word: 'impossible',
            phonetic: '/im\'posabal/',
            senses: [{ pos: 'adj.', meaning: '不可能发生的;办不到的' }],
          },
          {
            id: 'g8a-u1-w36',
            word: 'possible',
            phonetic: '/ppsabal/',
            senses: [{ pos: 'adj.', meaning: '可能的，可能做到的，可能实现的' }],
          },
          {
            id: 'g8a-u1-w37',
            word: 'nothing',
            phonetic: '/\'nAθir/',
            senses: [{ pos: 'pron.', meaning: '没有任何东西;没有事' }],
          },
          {
            id: 'g8a-u1-w38',
            word: 'silver',
            phonetic: '/\'silva/',
            senses: [{ pos: 'adj.', meaning: '银制的，银质的' }],
          },
          {
            id: 'g8a-u1-w39',
            word: 'British',
            phonetic: '/brrtj/',
            senses: [{ pos: 'adj.', meaning: '英国的;英国人的' }],
          },
          {
            id: 'g8a-u1-w40',
            word: 'the silver screen',
            senses: [{ pos: '', meaning: '电影业' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u1-w41',
            word: 'doubt',
            phonetic: '/daut/',
            senses: [{ pos: 'n.', meaning: '不确定，怀疑' }, { pos: 'v.', meaning: '怀疑，不相信，不信任' }],
          },
          {
            id: 'g8a-u1-w42',
            word: 'fear',
            phonetic: '/fia/',
            senses: [{ pos: 'n.', meaning: '害怕，恐惧;担忧' }],
          },
          {
            id: 'g8a-u1-w43',
            word: 'succeed',
            phonetic: '/sak\'si:d/',
            senses: [{ pos: 'v.', meaning: '成功，达成' }],
          },
          {
            id: 'g8a-u1-w44',
            word: 'excellent',
            phonetic: '/eksalant/',
            senses: [{ pos: 'adj.', meaning: '卓越的;极好的' }],
          },
          {
            id: 'g8a-u1-w45',
            word: 'ever',
            phonetic: '/eva/',
            senses: [{ pos: 'adv.', meaning: '在(以前)任何时候;从来' }],
          },
          {
            id: 'g8a-u1-w46',
            word: 'second',
            phonetic: '/\'sekand/',
            senses: [{ pos: 'n.', meaning: '秒' }],
          },
          {
            id: 'g8a-u1-w47',
            word: 'satisfied',
            phonetic: '/\'saetasfard/',
            senses: [{ pos: 'adj.', meaning: '满意的满足的' }],
          },
          {
            id: 'g8a-u1-w48',
            word: 'risky',
            phonetic: '/\'riski/',
            senses: [{ pos: 'adj.', meaning: '有危险的，有风险的' }],
          },
          {
            id: 'g8a-u1-w49',
            word: 'zero',
            phonetic: '/\'zierau/',
            senses: [{ pos: 'num.', meaning: '零' }],
          },
          {
            id: 'g8a-u1-w50',
            word: 'such',
            phonetic: '/sAtf/',
            senses: [{ pos: 'det.', meaning: '这样的;这种的;如此的' }],
          },
          {
            id: 'g8a-u1-w51',
            word: 'Olympics',
            phonetic: '/lmpiks/',
            senses: [{ pos: 'n.', meaning: '奥林匹克运动会，奥运会' }],
          },
          {
            id: 'g8a-u1-w52',
            word: 'athlete',
            phonetic: '/a0li:t/',
            senses: [{ pos: 'n.', meaning: '运动员;田径运动员' }],
          },
          {
            id: 'g8a-u1-w53',
            word: 'Olympic',
            phonetic: '/\'lmpk/',
            senses: [{ pos: 'adj.', meaning: '奥林匹克运动会的，奥运会的' }],
          },
          {
            id: 'g8a-u1-w54',
            word: 'youngster',
            phonetic: '/jansta/',
            senses: [{ pos: 'n.', meaning: '年轻人' }],
          },
          {
            id: 'g8a-u1-w55',
            word: 'stick',
            phonetic: '/stik/',
            senses: [{ pos: 'v.', meaning: '粘，贴' }],
          },
          {
            id: 'g8a-u1-w56',
            word: 'stickto',
            senses: [{ pos: '', meaning: '坚持' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u1-w57',
            word: 'superman',
            phonetic: '/\'su:paman/',
            senses: [{ pos: 'n.', meaning: '超人' }],
          },
