          {
            id: 'g8a-u2-w1',
            word: 'selfish',
            phonetic: '/\'selfiy/',
            senses: [{ pos: 'adj.', meaning: '自私的，自私自利的' }],
          },
          {
            id: 'g8a-u2-w2',
            word: 'giant',
            phonetic: '/\'d3arant/',
            senses: [{ pos: 'n.', meaning: '(儿童故事中的)巨人' }],
          },
          {
            id: 'g8a-u2-w3',
            word: 'shout',
            phonetic: '/Saut/',
            senses: [{ pos: 'v.', meaning: '大声说，喊叫，呼喊' }],
          },
          {
            id: 'g8a-u2-w4',
            word: 'gate',
            phonetic: '/geit/',
            senses: [{ pos: 'n.', meaning: '大门' }],
          },
          {
            id: 'g8a-u2-w5',
            word: 'build',
            phonetic: '/bild/',
            senses: [{ pos: 'v.', meaning: '建造，盖;造' }],
          },
          {
            id: 'g8a-u2-w6',
            word: 'since',
            phonetic: '/sins/',
            senses: [{ pos: 'prep.', meaning: '自从......以来，自从......之后' }],
          },
          {
            id: 'g8a-u2-w7',
            word: 'nor',
            phonetic: '/no:/',
            senses: [{ pos: 'conj.', meaning: '也不' }],
          },
          {
            id: 'g8a-u2-w8',
            word: 'hole',
            phonetic: '/haul/',
            senses: [{ pos: 'n.', meaning: '洞，孔' }],
          },
          {
            id: 'g8a-u2-w9',
            word: 'glad',
            phonetic: '/glaed/',
            senses: [{ pos: 'adj.', meaning: '高兴的，开心的' }],
          },
          {
            id: 'g8a-u2-w10',
            word: 'knock',
            phonetic: '/npk/',
            senses: [{ pos: 'v.', meaning: '碰撞;碰倒，撞倒' }],
          },
          {
            id: 'g8a-u2-w11',
            word: 'knock down',
            senses: [{ pos: '', meaning: '摧毁，拆毁' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u2-w12',
            word: 'afraid',
            phonetic: '/\'frerd/',
            senses: [{ pos: 'adj.', meaning: '害怕的，恐惧的' }],
          },
          {
            id: 'g8a-u2-w13',
            word: 'fear',
            phonetic: '/fie/',
            senses: [{ pos: 'v.', meaning: '害怕，恐惧;担心' }],
          },
          {
            id: 'g8a-u2-w14',
            word: 'double',
            phonetic: '/dAbal/',
            senses: [{ pos: 'adj.', meaning: '双倍的，两倍的' }],
          },
          {
            id: 'g8a-u2-w15',
            word: 'similar',
            phonetic: '/\'smale/',
            senses: [{ pos: 'adj.', meaning: '相似的，近似的，类似的' }],
          },
          {
            id: 'g8a-u2-w16',
            word: 'message',
            phonetic: '/mesid3/',
            senses: [{ pos: 'n.', meaning: '(电影、书籍、讲话等的)要旨,主题思想,寓意' }],
          },
          {
            id: 'g8a-u2-w17',
            word: 'action',
            phonetic: '/\'ækfen/',
            senses: [{ pos: 'n.', meaning: '情节' }],
          },
          {
            id: 'g8a-u2-w18',
            word: 'climax',
            phonetic: '/klaimæks/',
            senses: [{ pos: 'n.', meaning: '高潮' }],
          },
          {
            id: 'g8a-u2-w19',
            word: 'return',
            phonetic: '/ri\'t3:n/',
            senses: [{ pos: 'v.', meaning: '返回,回来,回去' }],
          },
          {
            id: 'g8a-u2-w20',
            word: 'lively',
            phonetic: '/larvli/',
            senses: [{ pos: 'adj.', meaning: '充满活力的,生气勃勃的' }],
          },
          {
            id: 'g8a-u2-w21',
            word: 'theirs',
            phonetic: '/oeaz/',
            senses: [{ pos: 'pron.', meaning: '他们的,她们的' }],
          },
          {
            id: 'g8a-u2-w22',
            word: 'grade',
            phonetic: '/greid/',
            senses: [{ pos: 'n.', meaning: '年级' }],
          },
          {
            id: 'g8a-u2-w23',
            word: 'priceless',
            phonetic: '/\'praisləs/',
            senses: [{ pos: 'adj.', meaning: '极其贵重的;无价的' }],
          },
          {
            id: 'g8a-u2-w24',
            word: 'past',
            phonetic: '/pa:st/',
            senses: [{ pos: 'adj.', meaning: '以前的,过去的,曾经的' }],
          },
          {
            id: 'g8a-u2-w25',
            word: 'offer',
            phonetic: '/pfa/',
            senses: [{ pos: 'v.', meaning: '提供,给予' }],
          },
          {
            id: 'g8a-u2-w26',
            word: 'quite',
            phonetic: '/kwait/',
            senses: [{ pos: 'adv.', meaning: '很;较为' }],
          },
          {
            id: 'g8a-u2-w27',
            word: 'stressed',
            phonetic: '/strest/',
            senses: [{ pos: 'adj.', meaning: '焦虑的,紧张的,无法放松的' }],
          },
          {
            id: 'g8a-u2-w28',
            word: 'recently',
            phonetic: '/\'ri:santli/',
            senses: [{ pos: 'adv.', meaning: '最近,近来,不久前' }],
          },
          {
            id: 'g8a-u2-w29',
            word: 'online',
            phonetic: '/\'Dnlam/',
            senses: [{ pos: 'adv.', meaning: '从网上,在网上' }],
          },
          {
            id: 'g8a-u2-w30',
            word: 'discuss',
            phonetic: '/dr\'skas/',
            senses: [{ pos: 'v.', meaning: '商讨,谈论,讨论' }],
          },
          {
            id: 'g8a-u2-w31',
            word: 'ticket',
            phonetic: '/\'tikit/',
            senses: [{ pos: 'n.', meaning: '票,入场券' }],
          },
          {
            id: 'g8a-u2-w32',
            word: 'guess',
            phonetic: '/ges/',
            senses: [{ pos: 'v.', meaning: '猜,猜测' }],
          },
          {
            id: 'g8a-u2-w33',
            word: 'I guess',
            senses: [{ pos: '', meaning: '我想,我认为' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u2-w34',
            word: 'suggestion',
            phonetic: '/sə\'d3estfən/',
            senses: [{ pos: 'n.', meaning: '建议,提议' }],
          },
          {
            id: 'g8a-u2-w35',
            word: 'explain',
            phonetic: '/ik\'splem/',
            senses: [{ pos: 'v.', meaning: '解释,说明' }],
          },
          {
            id: 'g8a-u2-w36',
            word: 'true',
            phonetic: '/tru:/',
            senses: [{ pos: 'adj.', meaning: '真正的' }],
          },
          {
            id: 'g8a-u2-w37',
            word: 'respect',
            phonetic: '/ri\'spekt/',
            senses: [{ pos: 'v.', meaning: '尊重,顾及' }],
          },
          {
            id: 'g8a-u2-w38',
            word: 'narrow',
            phonetic: '/\'næreu/',
            senses: [{ pos: 'adj.', meaning: '狭窄的' }],
          },
          {
            id: 'g8a-u2-w39',
            word: 'lane',
            phonetic: '/lem/',
            senses: [{ pos: 'n.', meaning: '巷(常用于路名中)' }],
          },
          {
            id: 'g8a-u2-w40',
            word: 'common',
            phonetic: '/\'komen/',
            senses: [{ pos: 'adj.', meaning: '常见的,普遍的' }],
          },
          {
            id: 'g8a-u2-w41',
            word: 'unit',
            phonetic: '/ju:nit/',
            senses: [{ pos: 'n.', meaning: '(计量用的)单位' }],
          },
          {
            id: 'g8a-u2-w42',
            word: 'perhaps',
            phonetic: '/pe\'hæps/',
            senses: [{ pos: 'adv.', meaning: '可能,大概,也许' }],
          },
          {
            id: 'g8a-u2-w43',
            word: 'argue',
            phonetic: '/a:gju:/',
            senses: [{ pos: 'v.', meaning: '争论,争吵' }],
          },
          {
            id: 'g8a-u2-w44',
            word: 'divide',
            phonetic: '/də\'vaid/',
            senses: [{ pos: 'v.', meaning: '(把.....)分开' }],
          },
          {
            id: 'g8a-u2-w45',
            word: 'dividing line',
            senses: [{ pos: '', meaning: '分界线,界限' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u2-w46',
            word: 'reach',
            phonetic: '/ri:ts/',
            senses: [{ pos: 'v.', meaning: '实现,达成' }],
          },
          {
            id: 'g8a-u2-w47',
            word: 'agreement',
            phonetic: '/a\'gri:mənt/',
            senses: [{ pos: 'n.', meaning: '(意见的)一致,相合' }],
          },
          {
            id: 'g8a-u2-w48',
            word: 'relative',
            phonetic: '/\'relətiv/',
            senses: [{ pos: 'n.', meaning: '家人;亲戚' }],
          },
          {
            id: 'g8a-u2-w49',
            word: 'government',
            phonetic: '/gлvəmənt/',
            senses: [{ pos: 'n.', meaning: '政府' }],
          },
          {
            id: 'g8a-u2-w50',
            word: 'poem',
            phonetic: '/pauim/',
            senses: [{ pos: 'n.', meaning: '诗;韵文' }],
          },
          {
            id: 'g8a-u2-w51',
            word: 'inside',
            phonetic: '/in\'said/',
            senses: [{ pos: 'adv.', meaning: '在(容器或其他封闭的空间)里面' }],
          },
          {
            id: 'g8a-u2-w52',
            word: 'neighbour',
            phonetic: '/neiba/',
            senses: [{ pos: 'n.', meaning: '邻居,邻人' }],
          },
          {
            id: 'g8a-u2-w53',
            word: 'drift',
            phonetic: '/drift/',
            senses: [{ pos: 'v.', meaning: '不知不觉地转变' }],
          },
          {
            id: 'g8a-u2-w54',
            word: 'ashamed',
            phonetic: '/a\'seimd/',
            senses: [{ pos: 'adj.', meaning: '羞耻的,内疚的,惭愧的' }],
          },
          {
            id: 'g8a-u2-w55',
            word: 'step',
            phonetic: '/step/',
            senses: [{ pos: 'v.', meaning: '跨步,迈步' }],
          },
          {
            id: 'g8a-u2-w56',
            word: 'act',
            phonetic: '/ækt/',
            senses: [{ pos: 'n.', meaning: '行为,行为,行动,动作,举动' }],
          },
          {
            id: 'g8a-u2-w57',
            word: 'same',
            phonetic: '/seim/',
            senses: [{ pos: 'adj.', meaning: '相同的' }],
          },
          {
            id: 'g8a-u2-w58',
            word: 'another',
            phonetic: '/a\'nnoal/',
            senses: [{ pos: 'det.', meaning: '另一,又一' }],
          },
          {
            id: 'g8a-u2-w59',
            word: 'pass',
            phonetic: '/pa:s/',
            senses: [{ pos: 'v.', meaning: '过去,流逝' }],
          },
          {
            id: 'g8a-u2-w60',
            word: 'whenever',
            phonetic: '/wen\'eve/',
            senses: [{ pos: 'conj.', meaning: '每当' }],
          },
