          {
            id: 'g8a-u3-w1',
            word: 'fair',
            phonetic: '/fea/',
            senses: [{ pos: 'n.', meaning: '展览会' }],
          },
          {
            id: 'g8a-u3-w2',
            word: 'block',
            phonetic: '/blok/',
            senses: [{ pos: 'n.', meaning: '一块(指木头、石头等有直边的硬物)' }],
          },
          {
            id: 'g8a-u3-w3',
            word: 'artificial',
            phonetic: '/a:tı\'fisəl/',
            senses: [{ pos: 'adj.', meaning: '人造的,人工的' }],
          },
          {
            id: 'g8a-u3-w4',
            word: 'hook',
            phonetic: '/huk/',
            senses: [{ pos: 'n.', meaning: '钩状物' }],
          },
          {
            id: 'g8a-u3-w5',
            word: 'cost',
            phonetic: '/kDSt/',
            senses: [{ pos: 'v.', meaning: '价格为,需支付(某一数量的钱)' }],
          },
          {
            id: 'g8a-u3-w6',
            word: 'condition',
            phonetic: '/ken\'difen/',
            senses: [{ pos: 'n.', meaning: '状况,状态;条件' }],
          },
          {
            id: 'g8a-u3-w7',
            word: 'blowsbaway',
            senses: [{ pos: '', meaning: '使某人大为惊讶' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u3-w8',
            word: 'lend',
            phonetic: '/lend/',
            senses: [{ pos: 'v.', meaning: '借给,借给,借出' }],
          },
          {
            id: 'g8a-u3-w9',
            word: 'lend(sb) a hand',
            senses: [{ pos: '', meaning: '帮助(某人)做事;(给某人)搭把手' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u3-w10',
            word: 'improve',
            phonetic: '/im\'pru:v/',
            senses: [{ pos: 'v.', meaning: '改善,改进;变得更好' }],
          },
          {
            id: 'g8a-u3-w11',
            word: '3-D',
            phonetic: '/,0ri:\'di:/',
            senses: [{ pos: 'adj.', meaning: '三维的,立体的' }],
          },
          {
            id: 'g8a-u3-w12',
            word: 'printer',
            phonetic: '/printa/',
            senses: [{ pos: 'n.', meaning: '打印机' }],
          },
          {
            id: 'g8a-u3-w13',
            word: 'invent',
            phonetic: '/in\'vent/',
            senses: [{ pos: 'v.', meaning: '发明,创造' }],
          },
          {
            id: 'g8a-u3-w14',
            word: 'signal',
            phonetic: '/\'signal/',
            senses: [{ pos: 'n.', meaning: '信号' }],
          },
          {
            id: 'g8a-u3-w15',
            word: 'weigh',
            phonetic: '/wer/',
            senses: [{ pos: 'v.', meaning: '重,重量是.....' }],
          },
          {
            id: 'g8a-u3-w16',
            word: 'kilogram',
            phonetic: '/\'kiləgræm/',
            senses: [{ pos: 'n.', meaning: '千克,公斤' }],
          },
          {
            id: 'g8a-u3-w17',
            word: 'fix',
            phonetic: '/fiks/',
            senses: [{ pos: 'v.', meaning: '解决(问题)' }],
          },
          {
            id: 'g8a-u3-w18',
            word: 'one after another',
            senses: [{ pos: '', meaning: '一个接一个' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u3-w19',
            word: 'invention',
            phonetic: '/in\'venfan/',
            senses: [{ pos: 'n.', meaning: '发明(物)' }],
          },
          {
            id: 'g8a-u3-w20',
            word: 'download',
            phonetic: '/daun\'ləud/',
            senses: [{ pos: 'v.', meaning: '下载' }],
          },
          {
            id: 'g8a-u3-w21',
            word: 'allow',
            phonetic: '/a\'lau/',
            senses: [{ pos: 'v.', meaning: '允许,容许,准许' }],
          },
          {
            id: 'g8a-u3-w22',
            word: 'solve',
            phonetic: '/splv/',
            senses: [{ pos: 'v.', meaning: '解决' }],
          },
          {
            id: 'g8a-u3-w23',
            word: 'blind',
            phonetic: '/blaind/',
            senses: [{ pos: 'adj.', meaning: '盲的,失明的' }],
          },
          {
            id: 'g8a-u3-w24',
            word: 'machine',
            phonetic: '/ma\'ji:n/',
            senses: [{ pos: 'n.', meaning: '机器' }],
          },
          {
            id: 'g8a-u3-w25',
            word: 'warn',
            phonetic: '/wo:n/',
            senses: [{ pos: 'v.', meaning: '警告,告诫;提醒' }],
          },
          {
            id: 'g8a-u3-w26',
            word: 'object',
            phonetic: '/\'pbd3ikt/',
            senses: [{ pos: 'n.', meaning: '物体' }],
          },
          {
            id: 'g8a-u3-w27',
            word: 'sense',
            phonetic: '/sens/',
            senses: [{ pos: 'v.', meaning: '检测出' }],
          },
          {
            id: 'g8a-u3-w28',
            word: 'congratulations',
            phonetic: '/kən grætsə\'leisənz/',
            senses: [{ pos: 'n.', meaning: '祝贺的话' }],
          },
          {
            id: 'g8a-u3-w29',
            word: 'everyday',
            phonetic: '/\'evrider/',
            senses: [{ pos: 'adj.', meaning: '日常的;平常的;每天的' }],
          },
          {
            id: 'g8a-u3-w30',
            word: 'trouble',
            phonetic: '/trabal/',
            senses: [{ pos: 'v.', meaning: '使忧虑,使苦恼' }],
          },
          {
            id: 'g8a-u3-w31',
            word: 'creative',
            phonetic: '/kri\'eitiv/',
            senses: [{ pos: 'adj.', meaning: '有创造力的' }],
          },
          {
            id: 'g8a-u3-w32',
            word: 'imaginative',
            phonetic: '/i\'mædzənətiv/',
            senses: [{ pos: 'adj.', meaning: '富有想象力的' }],
          },
          {
            id: 'g8a-u3-w33',
            word: 'inventor',
            phonetic: '/in\'venta/',
            senses: [{ pos: 'n.', meaning: '发明者,发明家' }],
          },
          {
            id: 'g8a-u3-w34',
            word: 'am',
            phonetic: '/ei\'em/',
            senses: [{ pos: '', meaning: '午前,上午' }],
          },
          {
            id: 'g8a-u3-w35',
            word: 'pm',
            phonetic: '/pi:\'em/',
            senses: [{ pos: '', meaning: '下午' }],
          },
          {
            id: 'g8a-u3-w36',
            word: 'glue',
            phonetic: '/glu:/',
            senses: [{ pos: 'n.', meaning: '胶,胶水' }],
          },
          {
            id: 'g8a-u3-w37',
            word: 'fail',
            phonetic: '/feil/',
            senses: [{ pos: 'v.', meaning: '失败' }],
          },
          {
            id: 'g8a-u3-w38',
            word: 'curiosity',
            phonetic: '/kjueri\'psəti/',
            senses: [{ pos: 'n.', meaning: '好奇心' }],
          },
          {
            id: 'g8a-u3-w39',
            word: 'once',
            phonetic: '/wAns/',
            senses: [{ pos: 'adv.', meaning: '过去,曾经' }],
          },
          {
            id: 'g8a-u3-w40',
            word: 'talent',
            phonetic: '/tælent/',
            senses: [{ pos: 'n.', meaning: '天资,天赋,才能' }],
          },
          {
            id: 'g8a-u3-w41',
            word: 'passionately',
            phonetic: '/\'pæsenətli/',
            senses: [{ pos: 'adv.', meaning: '强烈地' }],
          },
          {
            id: 'g8a-u3-w42',
            word: 'drive',
            phonetic: '/draiv/',
            senses: [{ pos: 'v.', meaning: '促使' }],
          },
          {
            id: 'g8a-u3-w43',
            word: 'detector',
            phonetic: '/di\'tekta/',
            senses: [{ pos: 'n.', meaning: '探测器,检测器' }],
          },
          {
            id: 'g8a-u3-w44',
            word: 'achievement',
            phonetic: '/a\'tfi:vmənt/',
            senses: [{ pos: 'n.', meaning: '成绩;成就' }],
          },
          {
            id: 'g8a-u3-w45',
            word: 'role',
            phonetic: '/rəul/',
            senses: [{ pos: 'n.', meaning: '作用' }],
          },
          {
            id: 'g8a-u3-w46',
            word: 'development',
            phonetic: '/di\'velapmənt/',
            senses: [{ pos: 'n.', meaning: '进步,发展' }],
          },
          {
            id: 'g8a-u3-w47',
            word: 'be drawn to',
            senses: [{ pos: '', meaning: '被.....吸引' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u3-w48',
            word: 'electricity',
            phonetic: '/i,lek\'trisəti/',
            senses: [{ pos: 'n.', meaning: '电' }],
          },
          {
            id: 'g8a-u3-w49',
            word: 'during',
            phonetic: '/\'djuarm/',
            senses: [{ pos: 'prep.', meaning: '在.....期间' }],
          },
          {
            id: 'g8a-u3-w50',
            word: 'more',
            phonetic: '/mə:/',
            senses: [{ pos: 'pron.', meaning: '另外的,更多的' }],
          },
          {
            id: 'g8a-u3-w51',
            word: 'lightning',
            phonetic: '/laitnin/',
            senses: [{ pos: 'n.', meaning: '闪电' }],
          },
          {
            id: 'g8a-u3-w52',
            word: 'lightning rod',
            senses: [{ pos: '', meaning: '避雷针' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u3-w53',
            word: 'pioneer',
            phonetic: '/paie\'nia/',
            senses: [{ pos: 'n.', meaning: '先驱,先驱,先锋,创始人' }],
          },
          {
            id: 'g8a-u3-w54',
            word: 'exploration',
            phonetic: '/eksplə\'reifən/',
            senses: [{ pos: 'n.', meaning: '探索;探险;勘探;勘查' }],
          },
          {
            id: 'g8a-u3-w55',
            word: 'test',
            phonetic: '/test/',
            senses: [{ pos: 'v.', meaning: '试验,检验' }],
          },
          {
            id: 'g8a-u3-w56',
            word: 'later',
            phonetic: '/\'leitə/',
            senses: [{ pos: 'adj.', meaning: '以后的' }],
          },
          {
            id: 'g8a-u3-w57',
            word: 'generation',
            phonetic: '/dzena\'reijan/',
            senses: [{ pos: 'n.', meaning: '一代(人)' }],
          },
