          {
            id: 'g9a-u4-w1',
            word: 'great-aunt',
            phonetic: '/greit\'a:nt/',
            senses: [{ pos: 'n.', meaning: '舅婆;姑婆;姨婆;叔祖母;伯祖母' }],
          },
          {
            id: 'g9a-u4-w2',
            word: 'person',
            phonetic: '/p3:sen/',
            senses: [{ pos: 'n.', meaning: 'Y' }],
          },
          {
            id: 'g9a-u4-w3',
            word: 'fighter',
            phonetic: '/faita/',
            senses: [{ pos: 'n.', meaning: '斗士,奋斗者' }],
          },
          {
            id: 'g9a-u4-w4',
            word: 'later',
            phonetic: '/\'leitə/',
            senses: [{ pos: 'adv.', meaning: '之后' }],
          },
          {
            id: 'g9a-u4-w5',
            word: 'footstep',
            phonetic: '/\'futstep/',
            senses: [{ pos: 'n.', meaning: '足迹' }],
          },
          {
            id: 'g9a-u4-w6',
            word: 'name...after',
            senses: [{ pos: '', meaning: '以.....的名字给......命名' }],
            isPhrase: true,
          },
          {
            id: 'g9a-u4-w7',
            word: 'realise',
            phonetic: '/\'rıəlaiz/',
            senses: [{ pos: 'v.', meaning: '明白;认识到' }],
          },
          {
            id: 'g9a-u4-w8',
            word: 'could',
            phonetic: '/kəd/',
            senses: [{ pos: 'v.', meaning: '能,可以' }],
          },
          {
            id: 'g9a-u4-w9',
            word: 'leave...behind',
            senses: [{ pos: '', meaning: '离开,丢下' }],
            isPhrase: true,
          },
          {
            id: 'g9a-u4-w10',
            word: 'gentle',
            phonetic: '/\'d3entl/',
            senses: [{ pos: 'adj.', meaning: '温和的,温柔的' }],
          },
          {
            id: 'g9a-u4-w11',
            word: 'pity',
            phonetic: '/prti/',
            senses: [{ pos: 'n.', meaning: '可惜,遗憾' }],
          },
          {
            id: 'g9a-u4-w12',
            word: 'war',
            phonetic: '/wo:/',
            senses: [{ pos: 'n.', meaning: '战争' }],
          },
          {
            id: 'g9a-u4-w13',
            word: 'battle',
            phonetic: '/\'bætl/',
            senses: [{ pos: 'n.', meaning: '战斗,战斗,战役' }],
          },
          {
            id: 'g9a-u4-w14',
            word: 'shock',
            phonetic: '/fok/',
            senses: [{ pos: 'n.', meaning: '令人震惊的事' }],
          },
          {
            id: 'g9a-u4-w15',
            word: 'survivor',
            phonetic: '/sə\'vaivə/',
            senses: [{ pos: 'n.', meaning: '生还者,幸存者' }],
          },
          {
            id: 'g9a-u4-w16',
            word: 'temperature',
            phonetic: '/temprətsə/',
            senses: [{ pos: 'n.', meaning: '温度,气温' }],
          },
          {
            id: 'g9a-u4-w17',
            word: 'front line',
            senses: [{ pos: '', meaning: '前线' }],
            isPhrase: true,
          },
          {
            id: 'g9a-u4-w18',
            word: 'lose',
            phonetic: '/lu:z/',
            senses: [{ pos: 'v.', meaning: '丧失,失去' }],
          },
          {
            id: 'g9a-u4-w19',
            word: 'post',
            phonetic: '/peust/',
            senses: [{ pos: 'n.', meaning: '岗位' }],
          },
          {
            id: 'g9a-u4-w20',
            word: 'deeply',
            phonetic: '/\'di:pli/',
            senses: [{ pos: 'adv.', meaning: '非常,很深地' }],
          },
          {
            id: 'g9a-u4-w21',
            word: 'presenter',
            phonetic: '/pri\'zenta/',
            senses: [{ pos: 'n.', meaning: '主持人,主持人,主播' }],
          },
          {
            id: 'g9a-u4-w22',
            word: 'recommend',
            phonetic: '/reka\'mend/',
            senses: [{ pos: 'v.', meaning: '推荐' }],
          },
          {
            id: 'g9a-u4-w23',
            word: 'co-pilot',
            phonetic: '/\'kəu,pailət/',
            senses: [{ pos: 'n.', meaning: '(飞机)副驾驶员' }],
          },
          {
            id: 'g9a-u4-w24',
            word: 'engine',
            phonetic: '/\'end3in/',
            senses: [{ pos: 'n.', meaning: '发动机,引擎' }],
          },
          {
            id: 'g9a-u4-w25',
            word: 'state',
            phonetic: '/stert/',
            senses: [{ pos: 'v.', meaning: '陈述;说明' }],
          },
          {
            id: 'g9a-u4-w26',
            word: 'dreamer',
            phonetic: '/dri:mə/',
            senses: [{ pos: 'n.', meaning: '做梦的人' }],
          },
          {
            id: 'g9a-u4-w27',
            word: 'pick',
            phonetic: '/pik/',
            senses: [{ pos: 'v.', meaning: '采,摘' }],
          },
          {
            id: 'g9a-u4-w28',
            word: 'countless',
            phonetic: '/\'kauntles/',
            senses: [{ pos: 'adj.', meaning: '无数的,数不尽的' }],
          },
          {
            id: 'g9a-u4-w29',
            word: 'thing',
            phonetic: '/0m/',
            senses: [{ pos: 'n.', meaning: '东西,物' }],
          },
          {
            id: 'g9a-u4-w30',
            word: 'experiment',
            phonetic: '/ik\'sperəmənt/',
            senses: [{ pos: 'n.', meaning: '实验' }],
          },
          {
            id: 'g9a-u4-w31',
            word: 'scientific research',
            senses: [{ pos: '', meaning: '科学研究' }],
            isPhrase: true,
          },
          {
            id: 'g9a-u4-w32',
            word: 'type',
            phonetic: '/taip/',
            senses: [{ pos: 'n.', meaning: '类型,种类' }],
          },
          {
            id: 'g9a-u4-w33',
            word: 'poor',
            phonetic: '/po:/',
            senses: [{ pos: 'adj.', meaning: '差的,不佳的' }],
          },
          {
            id: 'g9a-u4-w34',
            word: 'soil',
            phonetic: '/soil/',
            senses: [{ pos: 'n.', meaning: '土壤,土地,泥土' }],
          },
          {
            id: 'g9a-u4-w35',
            word: 'feed',
            phonetic: '/fi:d/',
            senses: [{ pos: 'v.', meaning: '养活' }],
          },
          {
            id: 'g9a-u4-w36',
            word: 'pass away',
            senses: [{ pos: '', meaning: '过世,离世' }],
            isPhrase: true,
          },
          {
            id: 'g9a-u4-w37',
            word: 'socialist',
            phonetic: '/\'seufelist/',
            senses: [{ pos: 'adj.', meaning: '社会主义的' }],
          },
