          {
            id: 'g8a-u5-w1',
            word: 'rule',
            phonetic: '/ru:l/',
            senses: [{ pos: 'n.', meaning: '规则' }],
          },
          {
            id: 'g8a-u5-w2',
            word: 'opposite',
            phonetic: '/\'ppəzət/',
            senses: [{ pos: 'prep.', meaning: '在.....的对面' }],
          },
          {
            id: 'g8a-u5-w3',
            word: 'packet',
            phonetic: '/pækit/',
            senses: [{ pos: 'n.', meaning: '小包,小袋' }],
          },
          {
            id: 'g8a-u5-w4',
            word: 'picnic',
            phonetic: '/\'piknik/',
            senses: [{ pos: 'n.', meaning: '野餐' }],
          },
          {
            id: 'g8a-u5-w5',
            word: 'smelly',
            phonetic: '/smeli/',
            senses: [{ pos: 'adj.', meaning: '有臭味的' }],
          },
          {
            id: 'g8a-u5-w6',
            word: 'cheese',
            phonetic: '/tfi:z/',
            senses: [{ pos: 'n.', meaning: '干酪,奶酪' }],
          },
          {
            id: 'g8a-u5-w7',
            word: 'block',
            phonetic: '/blok/',
            senses: [{ pos: 'v.', meaning: '阻挡' }],
          },
          {
            id: 'g8a-u5-w8',
            word: 'noise',
            phonetic: '/noiz/',
            senses: [{ pos: 'n.', meaning: '噪声;嘈杂声' }],
          },
          {
            id: 'g8a-u5-w9',
            word: 'reduce',
            phonetic: '/ri\'dju:s/',
            senses: [{ pos: 'v.', meaning: '减少;缩小;降低' }],
          },
          {
            id: 'g8a-u5-w10',
            word: 'kick',
            phonetic: '/kik/',
            senses: [{ pos: 'v.', meaning: '踢' }],
          },
          {
            id: 'g8a-u5-w11',
            word: 'seat',
            phonetic: '/si:t/',
            senses: [{ pos: 'n.', meaning: '座,座位' }],
          },
          {
            id: 'g8a-u5-w12',
            word: 'passenger',
            phonetic: '/\'pæsind3ə/',
            senses: [{ pos: 'n.', meaning: '乘客,旅客' }],
          },
          {
            id: 'g8a-u5-w13',
            word: 'anything',
            phonetic: '/eniem/',
            senses: [{ pos: 'pron.', meaning: '任何事物都（没有）' }],
          },
          {
            id: 'g8a-u5-w14',
            word: 'fool',
            phonetic: '/fu:l/',
            senses: [{ pos: 'n.', meaning: '蠢人,傻子,笨蛋' }],
          },
          {
            id: 'g8a-u5-w15',
            word: 'sign',
            phonetic: '/sam/',
            senses: [{ pos: 'n.', meaning: '标记;指示牌,标牌' }],
          },
          {
            id: 'g8a-u5-w16',
            word: 'clear',
            phonetic: '/kliə/',
            senses: [{ pos: 'v.', meaning: '清除;清理' }],
          },
          {
            id: 'g8a-u5-w17',
            word: 'throat',
            phonetic: '/0raut/',
            senses: [{ pos: 'n.', meaning: '喉咙,咽喉' }],
          },
          {
            id: 'g8a-u5-w18',
            word: 'clear sb\'s throat',
            senses: [{ pos: '', meaning: '(尤指说话前或为引人注意而)清清嗓子' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u5-w19',
            word: 'responsibility',
            phonetic: '/risponsə\'biləti/',
            senses: [{ pos: 'n.', meaning: '责任' }],
          },
          {
            id: 'g8a-u5-w20',
            word: 'behaviour',
            phonetic: '/bi\'hervja/',
            senses: [{ pos: 'n.', meaning: '行为,举止' }],
          },
          {
            id: 'g8a-u5-w21',
            word: 'belt',
            phonetic: '/belt/',
            senses: [{ pos: 'n.', meaning: '腰带,皮带' }],
          },
          {
            id: 'g8a-u5-w22',
            word: 'seat belt',
            senses: [{ pos: '', meaning: '安全带' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u5-w23',
            word: 'station',
            phonetic: '/steifan/',
            senses: [{ pos: 'n.', meaning: '车站' }],
          },
          {
            id: 'g8a-u5-w24',
            word: 'flowerpot',
            phonetic: '/flaueppt/',
            senses: [{ pos: 'n.', meaning: '花盆' }],
          },
          {
            id: 'g8a-u5-w25',
            word: 'mess',
            phonetic: '/mes/',
            senses: [{ pos: 'n.', meaning: '脏乱;凌乱' }],
          },
          {
            id: 'g8a-u5-w26',
            word: 'note',
            phonetic: '/naut/',
            senses: [{ pos: 'n.', meaning: '短笺,便条' }],
          },
          {
            id: 'g8a-u5-w27',
            word: 'honesty',
            phonetic: '/\'pnəsti/',
            senses: [{ pos: 'n.', meaning: '诚实,正直;坦诚' }],
          },
          {
            id: 'g8a-u5-w28',
            word: 'spread',
            phonetic: '/spred/',
            senses: [{ pos: 'v.', meaning: '传播' }],
          },
          {
            id: 'g8a-u5-w29',
            word: 'society',
            phonetic: '/saieti/',
            senses: [{ pos: 'n.', meaning: '社会' }],
          },
          {
            id: 'g8a-u5-w30',
            word: 'lawyer',
            phonetic: '/\'lo:je/',
            senses: [{ pos: 'n.', meaning: '律师' }],
          },
          {
            id: 'g8a-u5-w31',
            word: 'cause',
            phonetic: '/ko:z/',
            senses: [{ pos: 'v.', meaning: '导致,引起,使发生' }],
          },
          {
            id: 'g8a-u5-w32',
            word: 'accident',
            phonetic: '/\'æksident/',
            senses: [{ pos: 'n.', meaning: '交通事故;车祸' }],
          },
          {
            id: 'g8a-u5-w33',
            word: 'urgent',
            phonetic: '/\'з:d3ent/',
            senses: [{ pos: 'adj.', meaning: '紧急的,急迫的' }],
          },
          {
            id: 'g8a-u5-w34',
            word: 'nowadays',
            phonetic: '/\'nauedeiz/',
            senses: [{ pos: 'adv.', meaning: '现今,现时' }],
          },
          {
            id: 'g8a-u5-w35',
            word: 'a piece of cake',
            senses: [{ pos: '', meaning: '很容易的事情' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u5-w36',
            word: 'netizen',
            phonetic: '/\'netizan/',
            senses: [{ pos: 'n.', meaning: '网民' }],
          },
          {
            id: 'g8a-u5-w37',
            word: 'citizen',
            phonetic: '/\'sitizen/',
            senses: [{ pos: 'n.', meaning: '公民;市民,城镇居民' }],
          },
          {
            id: 'g8a-u5-w38',
            word: 'get in touch with',
            senses: [{ pos: '', meaning: '(与某人)取得联系' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u5-w39',
            word: 'click',
            phonetic: '/klik/',
            senses: [{ pos: 'n.', meaning: '点击(鼠标)' }],
          },
          {
            id: 'g8a-u5-w40',
            word: 'risk',
            phonetic: '/risk/',
            senses: [{ pos: 'n.', meaning: '危险(性),风险' }],
          },
          {
            id: 'g8a-u5-w41',
            word: 'basic',
            phonetic: '/\'beisik/',
            senses: [{ pos: 'adj.', meaning: '基础的,基本的,根本的' }],
          },
          {
            id: 'g8a-u5-w42',
            word: 'personal',
            phonetic: '/p3:senəl/',
            senses: [{ pos: 'adj.', meaning: '个人的,私人的' }],
          },
          {
            id: 'g8a-u5-w43',
            word: 'private',
            phonetic: '/\'praivət/',
            senses: [{ pos: 'adj.', meaning: '个人的,秘密的' }],
          },
          {
            id: 'g8a-u5-w44',
            word: 'avoid',
            phonetic: '/a\'vaid/',
            senses: [{ pos: 'v.', meaning: '避免' }],
          },
          {
            id: 'g8a-u5-w45',
            word: 'address',
            phonetic: '/ə\'dres/',
            senses: [{ pos: 'n.', meaning: '地址' }],
          },
          {
            id: 'g8a-u5-w46',
            word: 'ID',
            phonetic: '/ai\'di:/',
            senses: [{ pos: 'n.', meaning: '身份证明(文件)' }],
          },
          {
            id: 'g8a-u5-w47',
            word: 'passport',
            phonetic: '/pa:spo:t/',
            senses: [{ pos: 'n.', meaning: '护照' }],
          },
          {
            id: 'g8a-u5-w48',
            word: 'limit',
            phonetic: '/limit/',
            senses: [{ pos: 'v.', meaning: '限制,限定' }],
          },
          {
            id: 'g8a-u5-w49',
            word: 'password',
            phonetic: '/pa:sw3:d/',
            senses: [{ pos: 'n.', meaning: '密码' }],
          },
          {
            id: 'g8a-u5-w50',
            word: 'account',
            phonetic: '/a\'kaunt/',
            senses: [{ pos: 'n.', meaning: '账户' }],
          },
          {
            id: 'g8a-u5-w51',
            word: 'careless',
            phonetic: '/\'keələs/',
            senses: [{ pos: 'adj.', meaning: '不小心的,粗心的,疏忽的' }],
          },
          {
            id: 'g8a-u5-w52',
            word: 'aware',
            phonetic: '/a\'wea/',
            senses: [{ pos: 'adj.', meaning: '注意到的,察觉到的' }],
          },
          {
            id: 'g8a-u5-w53',
            word: 'stranger',
            phonetic: '/streind3ə/',
            senses: [{ pos: 'n.', meaning: '陌生人' }],
          },
          {
            id: 'g8a-u5-w54',
            word: 'cheat',
            phonetic: '/tfi:t/',
            senses: [{ pos: 'v.', meaning: '欺诈,欺骗' }],
          },
          {
            id: 'g8a-u5-w55',
            word: 'trust',
            phonetic: '/trast/',
            senses: [{ pos: 'v.', meaning: '信任,信赖,相信' }],
          },
          {
            id: 'g8a-u5-w56',
            word: 'enemy',
            phonetic: '/\'enami/',
            senses: [{ pos: 'n.', meaning: '敌人' }],
          },
          {
            id: 'g8a-u5-w57',
            word: 'behave',
            phonetic: '/bi\'herv/',
            senses: [{ pos: 'v.', meaning: '表现' }],
          },
          {
            id: 'g8a-u5-w58',
            word: 'cost',
            phonetic: '/kost/',
            senses: [{ pos: 'n.', meaning: '代价' }],
          },
          {
            id: 'g8a-u5-w59',
            word: 'cyberbullying',
            phonetic: '/saibə,bulim/',
            senses: [{ pos: 'n.', meaning: '网络霸凌(欺凌)' }],
          },
