          {
            id: 'g8a-u4-w1',
            word: 'digital',
            phonetic: '/\'did3ətl/',
            senses: [{ pos: 'adj.', meaning: '数字的,数码的' }],
          },
          {
            id: 'g8a-u4-w2',
            word: 'shock',
            phonetic: '/jpk/',
            senses: [{ pos: 'n.', meaning: '令人震惊的事' }],
          },
          {
            id: 'g8a-u4-w3',
            word: 'century',
            phonetic: '/sentfəri/',
            senses: [{ pos: 'n.', meaning: '世纪' }],
          },
          {
            id: 'g8a-u4-w4',
            word: 'ride',
            phonetic: '/raid/',
            senses: [{ pos: 'v.', meaning: '骑自行车' }, { pos: 'n.', meaning: '骑车旅行' }],
          },
          {
            id: 'g8a-u4-w5',
            word: 'shared bike',
            senses: [{ pos: '', meaning: '共享单车' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u4-w6',
            word: 'forever',
            phonetic: '/far\'eva/',
            senses: [{ pos: 'n.', meaning: '极长的一段时间' }],
          },
          {
            id: 'g8a-u4-w7',
            word: 'pound',
            phonetic: '/paund/',
            senses: [{ pos: 'n.', meaning: '英镑' }],
          },
          {
            id: 'g8a-u4-w8',
            word: 'quickly',
            phonetic: '/\'kwikli/',
            senses: [{ pos: 'adv.', meaning: '很快,马上' }],
          },
          {
            id: 'g8a-u4-w9',
            word: 'pay',
            phonetic: '/pel/',
            senses: [{ pos: 'v.', meaning: '付款' }],
          },
          {
            id: 'g8a-u4-w10',
            word: 'smartphone',
            phonetic: '/sma:tfəun/',
            senses: [{ pos: 'n.', meaning: '智能手机' }],
          },
          {
            id: 'g8a-u4-w11',
            word: 'shopkeeper',
            phonetic: '/sop,ki:pa/',
            senses: [{ pos: 'n.', meaning: '店主' }],
          },
          {
            id: 'g8a-u4-w12',
            word: 'wallet',
            phonetic: '/wolit/',
            senses: [{ pos: 'n.', meaning: '钱包' }],
          },
          {
            id: 'g8a-u4-w13',
            word: 'payment',
            phonetic: '/\'peimant/',
            senses: [{ pos: 'n.', meaning: '支付,付款' }],
          },
          {
            id: 'g8a-u4-w14',
            word: 'system',
            phonetic: '/\'sistim/',
            senses: [{ pos: 'n.', meaning: '系统' }],
          },
          {
            id: 'g8a-u4-w15',
            word: 'cash',
            phonetic: '/kæs/',
            senses: [{ pos: 'n.', meaning: '现款,现金' }],
          },
          {
            id: 'g8a-u4-w16',
            word: 'as',
            phonetic: '/az/',
            senses: [{ pos: 'conj.', meaning: '因为,由于' }],
          },
          {
            id: 'g8a-u4-w17',
            word: 'order',
            phonetic: '/\'o:da/',
            senses: [{ pos: 'v.', meaning: '点,要(食物或饮料)' }],
          },
          {
            id: 'g8a-u4-w18',
            word: 'app',
            phonetic: '/æp/',
            senses: [{ pos: 'n.', meaning: '应用程序,应用软件' }],
          },
          {
            id: 'g8a-u4-w19',
            word: 'delivery',
            phonetic: '/dı\'lıvari/',
            senses: [{ pos: 'n.', meaning: '递送' }],
          },
          {
            id: 'g8a-u4-w20',
            word: 'later',
            phonetic: '/leitə/',
            senses: [{ pos: 'adv.', meaning: '后来,随后,之后' }],
          },
          {
            id: 'g8a-u4-w21',
            word: 'heat',
            phonetic: '/hi:t/',
            senses: [{ pos: 'v.', meaning: '加热,使变热' }],
          },
          {
            id: 'g8a-u4-w22',
            word: 'oven',
            phonetic: '/\'Avan/',
            senses: [{ pos: 'n.', meaning: '烤箱,烤箱,烤炉' }],
          },
          {
            id: 'g8a-u4-w23',
            word: 'except',
            phonetic: '/ik\'sept/',
            senses: [{ pos: 'prep.', meaning: '除....之外' }],
          },
          {
            id: 'g8a-u4-w24',
            word: 'technology',
            phonetic: '/tek\'npləd3i/',
            senses: [{ pos: 'n.', meaning: '科技' }],
          },
          {
            id: 'g8a-u4-w25',
            word: 'more',
            phonetic: '/mo:/',
            senses: [{ pos: 'adv.', meaning: '更,更加,较为' }],
          },
          {
            id: 'g8a-u4-w26',
            word: 'convenient',
            phonetic: '/kən\'vi:niənt/',
            senses: [{ pos: 'adj.', meaning: '方便的,便利的' }],
          },
          {
            id: 'g8a-u4-w27',
            word: 'mobile',
            phonetic: '/\'məubail/',
            senses: [{ pos: 'adj.', meaning: '非固定的,移动式的' }],
          },
          {
            id: 'g8a-u4-w28',
            word: 'online',
            phonetic: '/\'onlam/',
            senses: [{ pos: 'adj.', meaning: '在线的,联网的' }],
          },
          {
            id: 'g8a-u4-w29',
            word: 'education',
            phonetic: '/edju\'kerfan/',
            senses: [{ pos: 'n.', meaning: '教育' }],
          },
          {
            id: 'g8a-u4-w30',
            word: 'anytime',
            phonetic: '/\'enitaim/',
            senses: [{ pos: 'adv.', meaning: '任何时候' }],
          },
          {
            id: 'g8a-u4-w31',
            word: 'anywhere',
            phonetic: '/eniweə/',
            senses: [{ pos: 'adv.', meaning: '任何地方,无论何处,随便哪里' }],
          },
          {
            id: 'g8a-u4-w32',
            word: 'check',
            phonetic: '/tfek/',
            senses: [{ pos: 'v.', meaning: '检查,核查' }],
          },
          {
            id: 'g8a-u4-w33',
            word: 'agreatdeal',
            senses: [{ pos: '', meaning: '充裕,丰富' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u4-w34',
            word: 'via',
            phonetic: '/\'vaie/',
            senses: [{ pos: 'prep.', meaning: '通过' }],
          },
          {
            id: 'g8a-u4-w35',
            word: 'course',
            phonetic: '/ko:s/',
            senses: [{ pos: 'n.', meaning: '课程' }],
          },
          {
            id: 'g8a-u4-w36',
            word: 'teach',
            phonetic: '/ti:tS/',
            senses: [{ pos: 'v.', meaning: '教' }],
          },
          {
            id: 'g8a-u4-w37',
            word: 'step',
            phonetic: '/step/',
            senses: [{ pos: 'n.', meaning: '步骤,措施' }],
          },
          {
            id: 'g8a-u4-w38',
            word: 'even',
            phonetic: '/i:van/',
            senses: [{ pos: 'adv.', meaning: '甚至' }],
          },
          {
            id: 'g8a-u4-w39',
            word: 'progress',
            phonetic: '/\'preugres/',
            senses: [{ pos: 'n.', meaning: '进步;进展' }],
          },
          {
            id: 'g8a-u4-w40',
            word: 'activity',
            phonetic: '/æk\'trvəti/',
            senses: [{ pos: 'n.', meaning: '活动' }],
          },
          {
            id: 'g8a-u4-w41',
            word: 'offline',
            phonetic: '/pf\'lam/',
            senses: [{ pos: 'adj.', meaning: '未联网的,不在线的' }],
          },
          {
            id: 'g8a-u4-w42',
            word: 'advantage',
            phonetic: '/ad\'va:ntid3/',
            senses: [{ pos: 'n.', meaning: '好处,优点' }],
          },
          {
            id: 'g8a-u4-w43',
            word: 'effect',
            phonetic: '/i\'fekt/',
            senses: [{ pos: 'n.', meaning: '效应;影响;结果' }],
          },
          {
            id: 'g8a-u4-w44',
            word: 'beglued to sth',
            senses: [{ pos: '', meaning: '盯着某物看' }],
            isPhrase: true,
          },
          {
            id: 'g8a-u4-w45',
            word: 'charge',
            phonetic: '/tfa:d3/',
            senses: [{ pos: 'v.', meaning: '(使)充电' }],
          },
          {
            id: 'g8a-u4-w46',
            word: 'real',
            phonetic: '/rıəl/',
            senses: [{ pos: 'adj.', meaning: '实际存在的,非想象的' }],
          },
          {
            id: 'g8a-u4-w47',
            word: 'strange',
            phonetic: '/streind3/',
            senses: [{ pos: 'adj.', meaning: '奇怪的,不寻常的;不可思议的' }],
          },
          {
            id: 'g8a-u4-w48',
            word: 'still',
            phonetic: '/stil/',
            senses: [{ pos: 'adj.', meaning: '静止的,不动的' }],
          },
          {
            id: 'g8a-u4-w49',
            word: 'just',
            phonetic: '/d3est/',
            senses: [{ pos: 'adv.', meaning: '只不过,只是' }],
          },
          {
            id: 'g8a-u4-w50',
            word: 'away',
            phonetic: '/a\'wei/',
            senses: [{ pos: 'adv.', meaning: '消失;移走' }],
          },
          {
            id: 'g8a-u4-w51',
            word: 'million',
            phonetic: '/\'miljen/',
            senses: [{ pos: 'num.', meaning: '极其庞大的数目许多,无数' }],
          },
          {
            id: 'g8a-u4-w52',
            word: 'would',
            phonetic: '/wud/',
            senses: [{ pos: 'v.', meaning: '会' }],
          },
          {
            id: 'g8a-u4-w53',
            word: 'anyone',
            phonetic: '/\'eniwan/',
            senses: [{ pos: 'pron.', meaning: '有人,任何人' }],
          },
          {
            id: 'g8a-u4-w54',
            word: 'person',
            phonetic: '/p3:san/',
            senses: [{ pos: 'n.', meaning: 'Y' }],
          },
          {
            id: 'g8a-u4-w55',
            word: 'bedroom',
            phonetic: '/\'bedrum/',
            senses: [{ pos: 'n.', meaning: '卧室' }],
          },
          {
            id: 'g8a-u4-w56',
            word: 'neighbourhood',
            phonetic: '/\'neibəhud/',
            senses: [{ pos: 'n.', meaning: '社区,住宅小区' }],
          },
