          {
            id: 'g7a-u2-w1',
            word: 'rock music',
            senses: [{ pos: '', meaning: '摇滚乐' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u2-w2',
            word: 'electric',
            phonetic: '/i\'lektrik/',
            senses: [{ pos: 'adj.', meaning: '用电的;电动的' }],
          },
          {
            id: 'g7a-u2-w3',
            word: 'guitar',
            phonetic: '/gi\'ta:/',
            senses: [{ pos: 'n.', meaning: '吉他' }],
          },
          {
            id: 'g7a-u2-w4',
            word: 'band',
            phonetic: '/bænd/',
            senses: [{ pos: 'n.', meaning: '乐队,乐团' }],
          },
          {
            id: 'g7a-u2-w5',
            word: 'sound',
            phonetic: '/saund/',
            senses: [{ pos: 'n.', meaning: '声音' }],
          },
          {
            id: 'g7a-u2-w6',
            word: 'different',
            phonetic: '/\'dıfərənt/',
            senses: [{ pos: 'adj.', meaning: '不同的,不一样的' }],
          },
          {
            id: 'g7a-u2-w7',
            word: 'suddenly',
            phonetic: '/sлdnli/',
            senses: [{ pos: 'adv.', meaning: '突然,突如其来地' }],
          },
          {
            id: 'g7a-u2-w8',
            word: 'hit',
            phonetic: '/hit/',
            senses: [{ pos: 'v.', meaning: '使(某人)突然意识到' }],
          },
          {
            id: 'g7a-u2-w9',
            word: 'rush',
            phonetic: '/rnf/',
            senses: [{ pos: 'v.', meaning: '冲,奔' }],
          },
          {
            id: 'g7a-u2-w10',
            word: 'festival',
            phonetic: '/festeval/',
            senses: [{ pos: 'n.', meaning: '(电影、戏剧、音乐等的)节,节庆,汇演' }],
          },
          {
            id: 'g7a-u2-w11',
            word: 'decide',
            phonetic: '/di\'said/',
            senses: [{ pos: 'v.', meaning: '决定' }],
          },
          {
            id: 'g7a-u2-w12',
            word: 'practice',
            phonetic: '/\'præktis/',
            senses: [{ pos: 'n.', meaning: '练习' }],
          },
          {
            id: 'g7a-u2-w13',
            word: 'stage',
            phonetic: '/steid3/',
            senses: [{ pos: 'n.', meaning: '舞台' }],
          },
          {
            id: 'g7a-u2-w14',
            word: 'nod',
            phonetic: '/npd/',
            senses: [{ pos: 'v.', meaning: '点头' }],
          },
          {
            id: 'g7a-u2-w15',
            word: 'instrument',
            phonetic: '/\'mstrəmənt/',
            senses: [{ pos: 'n.', meaning: '乐器' }],
          },
          {
            id: 'g7a-u2-w16',
            word: 'everybody',
            phonetic: '/evribodi/',
            senses: [{ pos: 'pron.', meaning: '每个人,人人' }],
          },
          {
            id: 'g7a-u2-w17',
            word: 'enjoy',
            phonetic: '/m\'d3ai/',
            senses: [{ pos: 'v.', meaning: '喜欢;享受......的乐趣' }],
          },
          {
            id: 'g7a-u2-w18',
            word: 'skate',
            phonetic: '/skert/',
            senses: [{ pos: 'v.', meaning: '滑冰,溜冰' }],
          },
          {
            id: 'g7a-u2-w19',
            word: 'club',
            phonetic: '/klab/',
            senses: [{ pos: 'n.', meaning: '俱乐部' }],
          },
          {
            id: 'g7a-u2-w20',
            word: 'volleyball',
            phonetic: '/volibo:l/',
            senses: [{ pos: 'n.', meaning: '排球(运动)' }],
          },
          {
            id: 'g7a-u2-w21',
            word: 'traditional',
            phonetic: '/trə\'difənəl/',
            senses: [{ pos: 'adj.', meaning: '传统的;习俗的;惯例的' }],
          },
          {
            id: 'g7a-u2-w22',
            word: 'paper-cutting',
            senses: [{ pos: '', meaning: '剪纸' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u2-w23',
            word: 'hold',
            phonetic: '/həuld/',
            senses: [{ pos: 'v.', meaning: '握住,抓住;抱住' }],
          },
          {
            id: 'g7a-u2-w24',
            word: 'ground',
            phonetic: '/graund/',
            senses: [{ pos: 'n.', meaning: '地,地面' }],
          },
          {
            id: 'g7a-u2-w25',
            word: 'weak',
            phonetic: '/wi:k/',
            senses: [{ pos: 'adj.', meaning: '虚弱的,不强壮的' }],
          },
          {
            id: 'g7a-u2-w26',
            word: 'high',
            phonetic: '/har/',
            senses: [{ pos: 'adj.', meaning: '高的' }],
          },
          {
            id: 'g7a-u2-w27',
            word: 'nature',
            phonetic: '/neitfa/',
            senses: [{ pos: 'n.', meaning: '大自然界' }],
          },
          {
            id: 'g7a-u2-w28',
            word: 'adventure',
            phonetic: '/ad\'ventfa/',
            senses: [{ pos: 'n.', meaning: '历险;奇遇' }],
          },
          {
            id: 'g7a-u2-w29',
            word: 'awake',
            phonetic: '/ə\'weik/',
            senses: [{ pos: 'adj.', meaning: '醒着的' }],
          },
          {
            id: 'g7a-u2-w30',
            word: 'midnight',
            phonetic: '/\'midnait/',
            senses: [{ pos: 'n.', meaning: '午夜' }],
          },
          {
            id: 'g7a-u2-w31',
            word: 'appear',
            phonetic: '/a\'pie/',
            senses: [{ pos: 'v.', meaning: '(尤指突然)出现,呈现' }],
          },
          {
            id: 'g7a-u2-w32',
            word: 'heart',
            phonetic: '/ha:t/',
            senses: [{ pos: 'n.', meaning: '心(脏)' }],
          },
          {
            id: 'g7a-u2-w33',
            word: 'almost',
            phonetic: '/\'o:lməust/',
            senses: [{ pos: 'adv.', meaning: '几乎,差不多' }],
          },
          {
            id: 'g7a-u2-w34',
            word: 'tap',
            phonetic: '/tæp/',
            senses: [{ pos: 'v.', meaning: '(用手指)轻拍,轻扣,轻叩,轻敲' }],
          },
          {
            id: 'g7a-u2-w35',
            word: 'shake',
            phonetic: '/feik/',
            senses: [{ pos: 'v.', meaning: '摇动' }],
          },
          {
            id: 'g7a-u2-w36',
            word: 'classmate',
            phonetic: '/\'kla:smeit/',
            senses: [{ pos: 'n.', meaning: '同班同学' }],
          },
          {
            id: 'g7a-u2-w37',
            word: 'lonely',
            phonetic: '/\'ləunli/',
            senses: [{ pos: 'adj.', meaning: '孤单的,寂寞的' }],
          },
          {
            id: 'g7a-u2-w38',
            word: 'magic',
            phonetic: '/\'mæd3ik/',
            senses: [{ pos: 'adj.', meaning: '有魔力的,神奇的' }],
          },
          {
            id: 'g7a-u2-w39',
            word: 'joy',
            phonetic: '/d3oi/',
            senses: [{ pos: 'n.', meaning: '欢欣,愉快,喜悦' }],
          },
          {
            id: 'g7a-u2-w40',
            word: 'notebook',
            phonetic: '/\'neutbuk/',
            senses: [{ pos: 'n.', meaning: '笔记本' }],
          },
          {
            id: 'g7a-u2-w41',
            word: 'shelf',
            phonetic: '/felf/',
            senses: [{ pos: 'n.', meaning: '搁板,架子' }],
          },
          {
            id: 'g7a-u2-w42',
            word: 'leave',
            phonetic: '/li:v/',
            senses: [{ pos: 'v.', meaning: '离开' }],
          },
          {
            id: 'g7a-u2-w43',
            word: 'page',
            phonetic: '/peid3/',
            senses: [{ pos: 'n.', meaning: '(书、报纸、文件等的)页,面' }],
          },
          {
            id: 'g7a-u2-w44',
            word: 'ending',
            phonetic: '/endin/',
            senses: [{ pos: 'n.', meaning: '(故事、电影、活动等的)结局,结尾' }],
          },
