          {
            id: 'g7a-u4-w1',
            word: 'unusual',
            phonetic: '/An\'ju:3uəl/',
            senses: [{ pos: 'adj.', meaning: '不平常的' }],
          },
          {
            id: 'g7a-u4-w2',
            word: 'university',
            phonetic: '/ju:na\'v3:səti/',
            senses: [{ pos: 'n.', meaning: '大学' }],
          },
          {
            id: 'g7a-u4-w3',
            word: 'treat',
            phonetic: '/tri:t/',
            senses: [{ pos: 'v.', meaning: '请客,款待,招待' }],
          },
          {
            id: 'g7a-u4-w4',
            word: 'realise',
            phonetic: '/\'rielaiz/',
            senses: [{ pos: 'v.', meaning: '知道;明白;认识到' }],
          },
          {
            id: 'g7a-u4-w5',
            word: 'dumpling',
            phonetic: '/\'damplin/',
            senses: [{ pos: 'n.', meaning: '水饺' }],
          },
          {
            id: 'g7a-u4-w6',
            word: 'whole',
            phonetic: '/həul/',
            senses: [{ pos: 'adj.', meaning: '整个的,全部的' }],
          },
          {
            id: 'g7a-u4-w7',
            word: 'cucumber',
            phonetic: '/\'kju:kambə/',
            senses: [{ pos: 'n.', meaning: '黄瓜' }],
          },
          {
            id: 'g7a-u4-w8',
            word: 'hang',
            phonetic: '/hærj/',
            senses: [{ pos: 'v.', meaning: '悬挂' }],
          },
          {
            id: 'g7a-u4-w9',
            word: 'balloon',
            phonetic: '/bə\'lu:n/',
            senses: [{ pos: 'n.', meaning: '气球' }],
          },
          {
            id: 'g7a-u4-w10',
            word: 'lantern',
            phonetic: '/\'læntən/',
            senses: [{ pos: 'n.', meaning: '灯笼;提灯' }],
          },
          {
            id: 'g7a-u4-w11',
            word: 'dish',
            phonetic: '/dij/',
            senses: [{ pos: 'n.', meaning: '(烹制好的)菜肴,一道菜' }],
          },
          {
            id: 'g7a-u4-w12',
            word: 'joke',
            phonetic: '/d3auk/',
            senses: [{ pos: 'v.', meaning: '说笑话;开玩笑' }],
          },
          {
            id: 'g7a-u4-w13',
            word: 'against the law',
            senses: [{ pos: '', meaning: '违法' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u4-w14',
            word: 'shocked',
            phonetic: '/fokt/',
            senses: [{ pos: 'adj.', meaning: '吃惊的,震惊的' }],
          },
          {
            id: 'g7a-u4-w15',
            word: 'laugh',
            phonetic: '/la:f/',
            senses: [{ pos: 'v.', meaning: '发出笑声,(大)笑' }],
          },
          {
            id: 'g7a-u4-w16',
            word: 'pork',
            phonetic: '/pa:k/',
            senses: [{ pos: 'n.', meaning: '猪肉' }],
          },
          {
            id: 'g7a-u4-w17',
            word: 'round',
            phonetic: '/raund/',
            senses: [{ pos: 'adj.', meaning: '圆形的,环形的' }],
          },
          {
            id: 'g7a-u4-w18',
            word: 'shape',
            phonetic: '/seip/',
            senses: [{ pos: 'n.', meaning: '形,形状,外形' }],
          },
          {
            id: 'g7a-u4-w19',
            word: 'reunion',
            phonetic: '/ri:\'ju:njen/',
            senses: [{ pos: 'n.', meaning: '团圆,团聚' }],
          },
          {
            id: 'g7a-u4-w20',
            word: 'piece',
            phonetic: '/pi:s/',
            senses: [{ pos: 'n.', meaning: '块;片;段;截' }],
          },
          {
            id: 'g7a-u4-w21',
            word: 'knife',
            phonetic: '/naif/',
            senses: [{ pos: 'n.', meaning: '刀' }],
          },
          {
            id: 'g7a-u4-w22',
            word: 'smell',
            phonetic: '/smel/',
            senses: [{ pos: 'n.', meaning: '气味' }],
          },
          {
            id: 'g7a-u4-w23',
            word: 'fill',
            phonetic: '/fil/',
            senses: [{ pos: 'v.', meaning: '弥漫,充满' }],
          },
          {
            id: 'g7a-u4-w24',
            word: 'Christmas',
            phonetic: '/\'krisməs/',
            senses: [{ pos: 'n.', meaning: '圣诞节(期间)' }],
          },
          {
            id: 'g7a-u4-w25',
            word: 'waste',
            phonetic: '/weist/',
            senses: [{ pos: 'n.', meaning: '废料,废弃物' }],
          },
          {
            id: 'g7a-u4-w26',
            word: 'throwaway',
            senses: [{ pos: '', meaning: '扔掉,丢弃' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u4-w27',
            word: 'pollution',
            phonetic: '/pa\'lu:fen/',
            senses: [{ pos: 'n.', meaning: '污染' }],
          },
          {
            id: 'g7a-u4-w28',
            word: 'plastic',
            phonetic: '/\'plæstik/',
            senses: [{ pos: 'adj.', meaning: '塑料制的' }],
          },
          {
            id: 'g7a-u4-w29',
            word: 'celebrate',
            phonetic: '/\'seləbreit/',
            senses: [{ pos: 'v.', meaning: '庆祝' }],
          },
          {
            id: 'g7a-u4-w30',
            word: 'meal',
            phonetic: '/mi:l/',
            senses: [{ pos: 'n.', meaning: '一餐;饭' }],
          },
          {
            id: 'g7a-u4-w31',
            word: 'duty',
            phonetic: '/dju:ti/',
            senses: [{ pos: 'n.', meaning: '职责,义务' }],
          },
          {
            id: 'g7a-u4-w32',
            word: 'shine',
            phonetic: '/fam/',
            senses: [{ pos: 'v.', meaning: '发光,发亮' }],
          },
          {
            id: 'g7a-u4-w33',
            word: 'usually',
            phonetic: '/ju:3uəli/',
            senses: [{ pos: 'adv.', meaning: '通常地;惯常地' }],
          },
          {
            id: 'g7a-u4-w34',
            word: 'break',
            phonetic: '/breik/',
            senses: [{ pos: 'n.', meaning: '中断,暂停' }],
          },
          {
            id: 'g7a-u4-w35',
            word: 'emergency',
            phonetic: '/i\'m3:d3ənsi/',
            senses: [{ pos: 'n.', meaning: '紧急情况,不测事件' }],
          },
          {
            id: 'g7a-u4-w36',
            word: 'miss',
            phonetic: '/mis/',
            senses: [{ pos: 'v.', meaning: '错过' }],
          },
          {
            id: 'g7a-u4-w37',
            word: 'thirsty',
            phonetic: '/\'03:sti/',
            senses: [{ pos: 'adj.', meaning: '渴的,口渴的' }],
          },
          {
            id: 'g7a-u4-w38',
            word: 'challenge',
            phonetic: '/tfælənd3/',
            senses: [{ pos: 'n.', meaning: '挑战,具有挑战性的事物' }],
          },
          {
            id: 'g7a-u4-w39',
            word: 'patient',
            phonetic: '/peisent/',
            senses: [{ pos: 'n.', meaning: '病人,患者' }],
          },
          {
            id: 'g7a-u4-w40',
            word: 'situation',
            phonetic: '/sitsu\'eifen/',
            senses: [{ pos: 'n.', meaning: '形势,情况,状况,局面' }],
          },
          {
            id: 'g7a-u4-w41',
            word: 'regret',
            phonetic: '/rr\'gret/',
            senses: [{ pos: 'v.', meaning: '后悔(做了某事);对......感到遗憾' }],
          },
          {
            id: 'g7a-u4-w42',
            word: 'decision',
            phonetic: '/di\'s13en/',
            senses: [{ pos: 'n.', meaning: '决定,抉择' }],
          },
          {
            id: 'g7a-u4-w43',
            word: 'support',
            phonetic: '/se\'po:t/',
            senses: [{ pos: 'n.', meaning: '支持' }],
          },
          {
            id: 'g7a-u4-w44',
            word: 'medical',
            phonetic: '/medikəl/',
            senses: [{ pos: 'adj.', meaning: '医学的;医疗的' }],
          },
          {
            id: 'g7a-u4-w45',
            word: 'firework',
            phonetic: '/faiew3:k/',
            senses: [{ pos: 'n.', meaning: '烟火,烟花' }],
          },
