          {
            id: 'g7a-u6-w1',
            word: 'pigeon',
            phonetic: '/pid3in/',
            senses: [{ pos: 'n.', meaning: '鸽子' }],
          },
          {
            id: 'g7a-u6-w2',
            word: 'surprise',
            phonetic: '/sa\'praiz/',
            senses: [{ pos: 'n.', meaning: '意想不到的事' }],
          },
          {
            id: 'g7a-u6-w3',
            word: 'knock around',
            senses: [{ pos: '', meaning: '(在某处)悠闲地度过' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u6-w4',
            word: 'droppings',
            phonetic: '/\'dropinz/',
            senses: [{ pos: 'n.', meaning: '(兽或鸟的)粪' }],
          },
          {
            id: 'g7a-u6-w5',
            word: 'boring',
            phonetic: '/\'bo:rin/',
            senses: [{ pos: 'adj.', meaning: '无趣的,无聊的,乏味的' }],
          },
          {
            id: 'g7a-u6-w6',
            word: 'feed',
            phonetic: '/fi:d/',
            senses: [{ pos: 'v.', meaning: '喂养,饲养,给......食物' }],
          },
          {
            id: 'g7a-u6-w7',
            word: 'madly',
            phonetic: '/\'mædli/',
            senses: [{ pos: 'adv.', meaning: '发狂地;无法控制地' }],
          },
          {
            id: 'g7a-u6-w8',
            word: 'scary',
            phonetic: '/skeəri/',
            senses: [{ pos: 'adj.', meaning: '可怕的,骇人的,恐怖的' }],
          },
          {
            id: 'g7a-u6-w9',
            word: 'research',
            phonetic: '/ri\'s3:tf/',
            senses: [{ pos: 'n.', meaning: '研究,调查' }],
          },
          {
            id: 'g7a-u6-w10',
            word: 'recognise',
            phonetic: '/\'rekegnaiz/',
            senses: [{ pos: 'v.', meaning: '认出;认识;辨认出' }],
          },
          {
            id: 'g7a-u6-w11',
            word: 'themselves',
            phonetic: '/oəm\'selvz/',
            senses: [{ pos: 'pron.', meaning: '它们自己;他们自己;她们自己' }],
          },
          {
            id: 'g7a-u6-w12',
            word: 'mirror',
            phonetic: '/\'mira/',
            senses: [{ pos: 'n.', meaning: '镜子' }],
          },
          {
            id: 'g7a-u6-w13',
            word: 'itself',
            phonetic: '/it\'self/',
            senses: [{ pos: 'pron.', meaning: '自己,自身' }],
          },
          {
            id: 'g7a-u6-w14',
            word: 'maybe',
            phonetic: '/\'meibi/',
            senses: [{ pos: 'adv.', meaning: '也许,大概,可能' }],
          },
          {
            id: 'g7a-u6-w15',
            word: 'several',
            phonetic: '/sevərəl/',
            senses: [{ pos: 'det.', meaning: '几个,一些' }],
          },
          {
            id: 'g7a-u6-w16',
            word: 'kilometre',
            phonetic: '/\'kılə,mi:tə/',
            senses: [{ pos: 'n.', meaning: '千米,公里' }],
          },
          {
            id: 'g7a-u6-w17',
            word: 'get lost',
            senses: [{ pos: '', meaning: '迷路' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u6-w18',
            word: 'speed',
            phonetic: '/spi:d/',
            senses: [{ pos: 'n.', meaning: '速度,速率' }],
          },
          {
            id: 'g7a-u6-w19',
            word: 'amazing',
            phonetic: '/a\'meizin/',
            senses: [{ pos: 'adj.', meaning: '惊人的;了不起的' }],
          },
          {
            id: 'g7a-u6-w20',
            word: 'enough',
            phonetic: '/i\'naf/',
            senses: [{ pos: 'pron.', meaning: '足够' }],
          },
          {
            id: 'g7a-u6-w21',
            word: 'beaver',
            phonetic: '/\'bi:və/',
            senses: [{ pos: 'n.', meaning: '河狸,海狸' }],
          },
          {
            id: 'g7a-u6-w22',
            word: 'wolf',
            phonetic: '/wulf/',
            senses: [{ pos: 'n.', meaning: '狼' }],
          },
          {
            id: 'g7a-u6-w23',
            word: 'engineer',
            phonetic: '/end3ə\'niə/',
            senses: [{ pos: 'n.', meaning: '工程师;设计师' }],
          },
          {
            id: 'g7a-u6-w24',
            word: 'hero',
            phonetic: '/\'hierəu/',
            senses: [{ pos: 'n.', meaning: '英雄' }],
          },
          {
            id: 'g7a-u6-w25',
            word: 'rescue',
            phonetic: '/\'reskju:/',
            senses: [{ pos: 'n.', meaning: '营救,救援' }],
          },
          {
            id: 'g7a-u6-w26',
            word: 'earthquake',
            phonetic: '/\'3:0kweik/',
            senses: [{ pos: 'n.', meaning: '地震' }],
          },
          {
            id: 'g7a-u6-w27',
            word: 'missing',
            phonetic: '/\'misin/',
            senses: [{ pos: 'adj.', meaning: '找不到的' }],
          },
          {
            id: 'g7a-u6-w28',
            word: 'save',
            phonetic: '/serv/',
            senses: [{ pos: 'v.', meaning: '救,拯救,挽救' }],
          },
          {
            id: 'g7a-u6-w29',
            word: 'dead',
            phonetic: '/ded/',
            senses: [{ pos: 'adj.', meaning: '死的,去世的' }],
          },
          {
            id: 'g7a-u6-w30',
            word: 'dodo',
            phonetic: '/deudau/',
            senses: [{ pos: 'n.', meaning: '渡渡鸟' }],
          },
          {
            id: 'g7a-u6-w31',
            word: 'as dead as a dodo',
            senses: [{ pos: '', meaning: '彻底死亡' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u6-w32',
            word: 'character',
            phonetic: '/\'kærəktə/',
            senses: [{ pos: 'n.', meaning: '(书、剧本、电影中的)人物,角色' }],
          },
          {
            id: 'g7a-u6-w33',
            word: 'museum',
            phonetic: '/mju:\'ziem/',
            senses: [{ pos: 'n.', meaning: '博物馆,博物院' }],
          },
          {
            id: 'g7a-u6-w34',
            word: 'island',
            phonetic: '/ailənd/',
            senses: [{ pos: 'n.', meaning: '岛屿' }],
          },
          {
            id: 'g7a-u6-w35',
            word: 'ocean',
            phonetic: '/\'aufen/',
            senses: [{ pos: 'n.', meaning: '海洋,大海' }],
          },
          {
            id: 'g7a-u6-w36',
            word: 'plenty',
            phonetic: '/plenti/',
            senses: [{ pos: 'pron.', meaning: '丰富,充足,众多,大量' }],
          },
          {
            id: 'g7a-u6-w37',
            word: 'friendly',
            phonetic: '/frendli/',
            senses: [{ pos: 'adj.', meaning: '友好的,友善的' }],
          },
          {
            id: 'g7a-u6-w38',
            word: 'peaceful',
            phonetic: '/pi:sfəl/',
            senses: [{ pos: 'adj.', meaning: '和平的,非暴力的' }],
          },
          {
            id: 'g7a-u6-w39',
            word: 'arrive',
            phonetic: '/a\'raiv/',
            senses: [{ pos: 'v.', meaning: '到达,抵达' }],
          },
          {
            id: 'g7a-u6-w40',
            word: 'forest',
            phonetic: '/\'fbrist/',
            senses: [{ pos: 'n.', meaning: '森林,林区' }],
          },
          {
            id: 'g7a-u6-w41',
            word: 'hunt',
            phonetic: '/hant/',
            senses: [{ pos: 'v.', meaning: '打猎杀' }],
          },
          {
            id: 'g7a-u6-w42',
            word: 'die out',
            senses: [{ pos: '', meaning: '消失;绝迹,灭绝' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u6-w43',
            word: 'full',
            phonetic: '/ful/',
            senses: [{ pos: 'adj.', meaning: '满是.......的' }],
          },
          {
            id: 'g7a-u6-w44',
            word: 'fantastic',
            phonetic: '/fæn\'tæstik/',
            senses: [{ pos: 'adj.', meaning: '极好的,吸引人的,有趣的' }],
          },
          {
            id: 'g7a-u6-w45',
            word: 'as happy as a clam',
            senses: [{ pos: '', meaning: '非常高兴的,相当满足的' }],
            isPhrase: true,
          },
