          {
            id: 'g7a-u3-w1',
            word: 'silent',
            phonetic: '/\'sailənt/',
            senses: [{ pos: 'adj.', meaning: '不作声的' }],
          },
          {
            id: 'g7a-u3-w2',
            word: 'along',
            phonetic: '/a\'lon/',
            senses: [{ pos: 'prep.', meaning: '顺着,沿着' }],
          },
          {
            id: 'g7a-u3-w3',
            word: 'mountain',
            phonetic: '/\'mauntin/',
            senses: [{ pos: 'n.', meaning: '高山,山岳' }],
          },
          {
            id: 'g7a-u3-w4',
            word: 'road',
            phonetic: '/rəud/',
            senses: [{ pos: 'n.', meaning: '路,道路,公路' }],
          },
          {
            id: 'g7a-u3-w5',
            word: 'handsome',
            phonetic: '/\'hænsəm/',
            senses: [{ pos: 'adj.', meaning: '(男子)英俊的,漂亮的' }],
          },
          {
            id: 'g7a-u3-w6',
            word: 'strict',
            phonetic: '/strikt/',
            senses: [{ pos: 'adj.', meaning: '严格的,严厉的' }],
          },
          {
            id: 'g7a-u3-w7',
            word: 'follow',
            phonetic: '/folau/',
            senses: [{ pos: 'v.', meaning: '跟着,跟随' }],
          },
          {
            id: 'g7a-u3-w8',
            word: 'postman',
            phonetic: '/\'peustmən/',
            senses: [{ pos: 'n.', meaning: '邮递员,邮差' }],
          },
          {
            id: 'g7a-u3-w9',
            word: 'touching',
            phonetic: '/\'tatsin/',
            senses: [{ pos: 'adj.', meaning: '感人的' }],
          },
          {
            id: 'g7a-u3-w10',
            word: 'son',
            phonetic: '/sAn/',
            senses: [{ pos: 'n.', meaning: '儿子' }],
          },
          {
            id: 'g7a-u3-w11',
            word: 'serve',
            phonetic: '/s3:v/',
            senses: [{ pos: 'v.', meaning: '为......工作;供职' }],
          },
          {
            id: 'g7a-u3-w12',
            word: 'area',
            phonetic: '/\'eəriə/',
            senses: [{ pos: 'n.', meaning: '(国家,市镇等的)地区,区域' }],
          },
          {
            id: 'g7a-u3-w13',
            word: 'absent',
            phonetic: '/æbsent/',
            senses: [{ pos: 'adj.', meaning: '不在的,缺席的' }],
          },
          {
            id: 'g7a-u3-w14',
            word: 'seldom',
            phonetic: '/seldəm/',
            senses: [{ pos: 'adv.', meaning: '很少,罕见,不常' }],
          },
          {
            id: 'g7a-u3-w15',
            word: 'position',
            phonetic: '/pa\'zijen/',
            senses: [{ pos: 'n.', meaning: '职位,职务' }],
          },
          {
            id: 'g7a-u3-w16',
            word: 'carry',
            phonetic: '/\'kæri/',
            senses: [{ pos: 'v.', meaning: '把(某物或某人)带至(新的地点或位置)' }],
          },
          {
            id: 'g7a-u3-w17',
            word: 'across',
            phonetic: '/a\'kros/',
            senses: [{ pos: 'prep.', meaning: '从一边到另一边;穿过' }],
          },
          {
            id: 'g7a-u3-w18',
            word: 'memory',
            phonetic: '/\'meməri/',
            senses: [{ pos: 'n.', meaning: '记忆,回忆' }],
          },
          {
            id: 'g7a-u3-w19',
            word: 'tear',
            phonetic: '/tiə/',
            senses: [{ pos: 'n.', meaning: '眼泪,泪水' }],
          },
          {
            id: 'g7a-u3-w20',
            word: 'growth',
            phonetic: '/grau0/',
            senses: [{ pos: 'n.', meaning: '(性格、智力或情感的)发展,成长' }],
          },
          {
            id: 'g7a-u3-w21',
            word: 'hide',
            phonetic: '/haid/',
            senses: [{ pos: 'v.', meaning: '把.....藏起来,隐藏' }],
          },
          {
            id: 'g7a-u3-w22',
            word: 'care',
            phonetic: '/kea/',
            senses: [{ pos: 'n.', meaning: '关心' }],
          },
          {
            id: 'g7a-u3-w23',
            word: 'hug',
            phonetic: '/hag/',
            senses: [{ pos: 'n.', meaning: '拥抱' }],
          },
          {
            id: 'g7a-u3-w24',
            word: 'kiss',
            phonetic: '/k1s/',
            senses: [{ pos: 'n.', meaning: '吻' }],
          },
          {
            id: 'g7a-u3-w25',
            word: 'marry',
            phonetic: '/\'mæri/',
            senses: [{ pos: 'v.', meaning: '结婚;娶;嫁' }],
          },
          {
            id: 'g7a-u3-w26',
            word: 'queen',
            phonetic: '/kwi:n/',
            senses: [{ pos: 'n.', meaning: '女王' }],
          },
          {
            id: 'g7a-u3-w27',
            word: 'pickup',
            senses: [{ pos: '', meaning: '搭载,接载' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u3-w28',
            word: 'actress',
            phonetic: '/\'æktris/',
            senses: [{ pos: 'n.', meaning: '女演员' }],
          },
          {
            id: 'g7a-u3-w29',
            word: 'change',
            phonetic: '/tfemd3/',
            senses: [{ pos: 'v.', meaning: '换(衣服)' }],
          },
          {
            id: 'g7a-u3-w30',
            word: 'race',
            phonetic: '/reis/',
            senses: [{ pos: 'v.', meaning: '比赛' }, { pos: 'n.', meaning: '比赛' }],
          },
          {
            id: 'g7a-u3-w31',
            word: 'serious',
            phonetic: '/\'sıəriəs/',
            senses: [{ pos: 'adj.', meaning: '严重的' }],
          },
          {
            id: 'g7a-u3-w32',
            word: 'disease',
            phonetic: '/dr\'zi:z/',
            senses: [{ pos: 'n.', meaning: '疾病,病' }],
          },
          {
            id: 'g7a-u3-w33',
            word: 'stay',
            phonetic: '/ster/',
            senses: [{ pos: 'v.', meaning: '停留,逗留,留下' }],
          },
          {
            id: 'g7a-u3-w34',
            word: 'trailer',
            phonetic: '/\'treilə/',
            senses: [{ pos: 'n.', meaning: '拖车,挂车' }],
          },
          {
            id: 'g7a-u3-w35',
            word: 'pull',
            phonetic: '/pul/',
            senses: [{ pos: 'v.', meaning: '拉;扯;拖' }],
          },
          {
            id: 'g7a-u3-w36',
            word: 'bright',
            phonetic: '/brait/',
            senses: [{ pos: 'adj.', meaning: '欢快的;充满生气的' }],
          },
          {
            id: 'g7a-u3-w37',
            word: 'smile',
            phonetic: '/smail/',
            senses: [{ pos: 'n.', meaning: '笑容' }],
          },
          {
            id: 'g7a-u3-w38',
            word: 'refuse',
            phonetic: '/ri\'fju:z/',
            senses: [{ pos: 'v.', meaning: '拒绝,回绝' }],
          },
          {
            id: 'g7a-u3-w39',
            word: 'result',
            phonetic: '/ri\'zalt/',
            senses: [{ pos: 'n.', meaning: '结果,后果' }],
          },
          {
            id: 'g7a-u3-w40',
            word: 'matter',
            phonetic: '/\'mæte/',
            senses: [{ pos: 'v.', meaning: '(尤指对某人自己或对发生之事)重要,要紧,有关系' }],
          },
          {
            id: 'g7a-u3-w41',
            word: 'power',
            phonetic: '/paue/',
            senses: [{ pos: 'v.', meaning: '给(车辆或机器)提供动力' }],
          },
