          {
            id: 'g7a-u1-w1',
            word: 'without',
            phonetic: '/wio\'aut/',
            senses: [{ pos: 'prep.', meaning: '缺乏,没有' }],
          },
          {
            id: 'g7a-u1-w2',
            word: 'sentence',
            phonetic: '/sentans/',
            senses: [{ pos: 'n.', meaning: '句子' }],
          },
          {
            id: 'g7a-u1-w3',
            word: 'pointout',
            senses: [{ pos: '', meaning: '指出,指明' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u1-w4',
            word: 'mistake',
            phonetic: '/mə\'steik/',
            senses: [{ pos: 'n.', meaning: '错误' }],
          },
          {
            id: 'g7a-u1-w5',
            word: 'polite',
            phonetic: '/pe\'lart/',
            senses: [{ pos: 'adj.', meaning: '有礼貌的,客气的' }],
          },
          {
            id: 'g7a-u1-w6',
            word: 'mind',
            phonetic: '/maind/',
            senses: [{ pos: 'n.', meaning: '头脑;思想,思维' }],
          },
          {
            id: 'g7a-u1-w7',
            word: 'hers',
            phonetic: '/h3:z/',
            senses: [{ pos: 'pron.', meaning: '她的' }],
          },
          {
            id: 'g7a-u1-w8',
            word: 'dry',
            phonetic: '/drai/',
            senses: [{ pos: 'adj.', meaning: '干的,干燥的' }],
          },
          {
            id: 'g7a-u1-w9',
            word: 'meaning',
            phonetic: '/\'mi:nin/',
            senses: [{ pos: 'n.', meaning: '意义,意思,含义' }],
          },
          {
            id: 'g7a-u1-w10',
            word: 'fact',
            phonetic: '/fækt/',
            senses: [{ pos: 'n.', meaning: '事实;真相' }],
          },
          {
            id: 'g7a-u1-w11',
            word: 'infact',
            senses: [{ pos: '', meaning: '事实上' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u1-w12',
            word: 'need',
            phonetic: '/ni:d/',
            senses: [{ pos: 'v.', meaning: '需要' }],
          },
          {
            id: 'g7a-u1-w13',
            word: 'remember',
            phonetic: '/ri\'memba/',
            senses: [{ pos: 'v.', meaning: '记住,记得' }],
          },
          {
            id: 'g7a-u1-w14',
            word: 'really',
            phonetic: '/rıəli/',
            senses: [{ pos: 'adv.', meaning: '确实地,的确' }],
          },
          {
            id: 'g7a-u1-w15',
            word: 'important',
            phonetic: '/im\'po:tent/',
            senses: [{ pos: 'adj.', meaning: '重要的,重大的' }],
          },
          {
            id: 'g7a-u1-w16',
            word: 'plan',
            phonetic: '/plæn/',
            senses: [{ pos: 'v.', meaning: '计划' }],
          },
          {
            id: 'g7a-u1-w17',
            word: 'problem',
            phonetic: '/\'probləm/',
            senses: [{ pos: 'n.', meaning: '问题,难题;困难' }],
          },
          {
            id: 'g7a-u1-w18',
            word: 'homework',
            phonetic: '/həumw3:k/',
            senses: [{ pos: 'n.', meaning: '家庭作业,功课' }],
          },
          {
            id: 'g7a-u1-w19',
            word: 'task',
            phonetic: '/ta:sk/',
            senses: [{ pos: 'n.', meaning: '工作,任务' }],
          },
          {
            id: 'g7a-u1-w20',
            word: 'project',
            phonetic: '/\'prod3ekt/',
            senses: [{ pos: 'n.', meaning: '(学校的)课题,研究项目' }],
          },
          {
            id: 'g7a-u1-w21',
            word: 'advice',
            phonetic: '/ed\'vais/',
            senses: [{ pos: 'n.', meaning: '意见,建议;忠告,劝告' }],
          },
          {
            id: 'g7a-u1-w22',
            word: 'journey',
            phonetic: '/\'d33:ni/',
            senses: [{ pos: 'n.', meaning: '旅行,旅程;历程,过程' }],
          },
          {
            id: 'g7a-u1-w23',
            word: 'something',
            phonetic: '/\'shmem/',
            senses: [{ pos: 'pron.', meaning: '某物;某事;某些东西' }],
          },
          {
            id: 'g7a-u1-w24',
            word: 'thought',
            phonetic: '/05:t/',
            senses: [{ pos: 'n.', meaning: '意见,主意,观点' }],
          },
          {
            id: 'g7a-u1-w25',
            word: 'life',
            phonetic: '/larf/',
            senses: [{ pos: 'n.', meaning: '生活' }],
          },
          {
            id: 'g7a-u1-w26',
            word: 'primary school',
            senses: [{ pos: '', meaning: '小学' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u1-w27',
            word: 'pool',
            phonetic: '/pu:l/',
            senses: [{ pos: 'n.', meaning: '水塘,水洼' }],
          },
          {
            id: 'g7a-u1-w28',
            word: 'protect',
            phonetic: '/pra\'tekt/',
            senses: [{ pos: 'v.', meaning: '保护;防护' }],
          },
          {
            id: 'g7a-u1-w29',
            word: 'wind',
            phonetic: '/wind/',
            senses: [{ pos: 'n.', meaning: '风' }],
          },
          {
            id: 'g7a-u1-w30',
            word: 'wide',
            phonetic: '/waid/',
            senses: [{ pos: 'adj.', meaning: '宽的,宽阔的' }],
          },
          {
            id: 'g7a-u1-w31',
            word: 'sail',
            phonetic: '/serl/',
            senses: [{ pos: 'v.', meaning: '驾驶(船只)' }],
          },
          {
            id: 'g7a-u1-w32',
            word: 'through',
            phonetic: '/oru:/',
            senses: [{ pos: 'prep.', meaning: '从一端至另一端,穿过,通过' }],
          },
          {
            id: 'g7a-u1-w33',
            word: 'storm',
            phonetic: '/sto:m/',
            senses: [{ pos: 'n.', meaning: '暴风雨(雪)' }],
          },
          {
            id: 'g7a-u1-w34',
            word: 'towards',
            phonetic: '/tə\'wo:dz/',
            senses: [{ pos: 'prep.', meaning: '向着,朝着(某个方向)' }],
          },
          {
            id: 'g7a-u1-w35',
            word: 'hope',
            phonetic: '/haup/',
            senses: [{ pos: 'v.', meaning: '希望,期望,指望' }],
          },
