          {
            id: 'g7a-u5-w1',
            word: 'within',
            phonetic: '/wio\'in/',
            senses: [{ pos: 'prep.', meaning: '在(建筑或地区)里' }],
          },
          {
            id: 'g7a-u5-w2',
            word: 'quarter',
            phonetic: '/\'kwo:tə/',
            senses: [{ pos: 'n.', meaning: '一刻钟,十五分钟' }],
          },
          {
            id: 'g7a-u5-w3',
            word: 'workshop',
            phonetic: '/\'w3:kspp/',
            senses: [{ pos: 'n.', meaning: '车间,工场' }],
          },
          {
            id: 'g7a-u5-w4',
            word: 'leaf',
            phonetic: '/li:f/',
            senses: [{ pos: 'n.', meaning: '叶,叶子' }],
          },
          {
            id: 'g7a-u5-w5',
            word: 'each',
            phonetic: '/i:ts/',
            senses: [{ pos: 'det.', meaning: '(两个或两个以上物或人中的)每个,各' }],
          },
          {
            id: 'g7a-u5-w6',
            word: 'collect',
            phonetic: '/kə\'lekt/',
            senses: [{ pos: 'v.', meaning: '收集,采集;使集中' }],
          },
          {
            id: 'g7a-u5-w7',
            word: 'root',
            phonetic: '/ru:t/',
            senses: [{ pos: 'n.', meaning: '根' }],
          },
          {
            id: 'g7a-u5-w8',
            word: 'send',
            phonetic: '/send/',
            senses: [{ pos: 'v.', meaning: '送出,发出' }],
          },
          {
            id: 'g7a-u5-w9',
            word: 'rise',
            phonetic: '/raiz/',
            senses: [{ pos: 'v.', meaning: '升高,上升' }],
          },
          {
            id: 'g7a-u5-w10',
            word: 'stem',
            phonetic: '/stem/',
            senses: [{ pos: 'n.', meaning: '(植物的)茎,梗,柄' }],
          },
          {
            id: 'g7a-u5-w11',
            word: 'mix',
            phonetic: '/miks/',
            senses: [{ pos: 'v.', meaning: '(使)混合' }],
          },
          {
            id: 'g7a-u5-w12',
            word: 'produce',
            phonetic: '/pra\'dju:s/',
            senses: [{ pos: 'v.', meaning: '(自然地)生产产生,出产' }],
          },
          {
            id: 'g7a-u5-w13',
            word: 'sugar',
            phonetic: '/fugə/',
            senses: [{ pos: 'n.', meaning: '糖' }],
          },
          {
            id: 'g7a-u5-w14',
            word: 'product',
            phonetic: '/prodakt/',
            senses: [{ pos: 'n.', meaning: '(自然过程或化学反应的)生成物' }],
          },
          {
            id: 'g7a-u5-w15',
            word: 'oxygen',
            phonetic: '/\'bksid3ən/',
            senses: [{ pos: 'n.', meaning: '氧' }],
          },
          {
            id: 'g7a-u5-w16',
            word: 'human',
            phonetic: '/hju:men/',
            senses: [{ pos: 'n.', meaning: '人类;人' }],
          },
          {
            id: 'g7a-u5-w17',
            word: 'though',
            phonetic: '/oau/',
            senses: [{ pos: 'adv.', meaning: '可是,不过,然而' }],
          },
          {
            id: 'g7a-u5-w18',
            word: 'breathe',
            phonetic: '/bri:0/',
            senses: [{ pos: 'v.', meaning: '呼吸' }],
          },
          {
            id: 'g7a-u5-w19',
            word: 'soon',
            phonetic: '/su:n/',
            senses: [{ pos: 'adv.', meaning: '不久,即刻,很快' }],
          },
          {
            id: 'g7a-u5-w20',
            word: 'dark',
            phonetic: '/da:k/',
            senses: [{ pos: 'adj.', meaning: '昏暗的;黑暗的' }],
          },
          {
            id: 'g7a-u5-w21',
            word: 'rest',
            phonetic: '/rest/',
            senses: [{ pos: 'n.', meaning: '休息(时间)' }],
          },
          {
            id: 'g7a-u5-w22',
            word: 'natural',
            phonetic: '/\'nætserəl/',
            senses: [{ pos: 'adj.', meaning: '自然的,天然的' }],
          },
          {
            id: 'g7a-u5-w23',
            word: 'seed',
            phonetic: '/si:d/',
            senses: [{ pos: 'n.', meaning: '种子,籽' }],
          },
          {
            id: 'g7a-u5-w24',
            word: 'grow',
            phonetic: '/grau/',
            senses: [{ pos: 'v.', meaning: '生长' }],
          },
          {
            id: 'g7a-u5-w25',
            word: 'part',
            phonetic: '/pa:t/',
            senses: [{ pos: 'n.', meaning: '部分' }],
          },
          {
            id: 'g7a-u5-w26',
            word: 'rainforest',
            phonetic: '/\'reinforist/',
            senses: [{ pos: 'n.', meaning: '(热带)雨林' }],
          },
          {
            id: 'g7a-u5-w27',
            word: 'culture',
            phonetic: '/\'kaltsa/',
            senses: [{ pos: 'n.', meaning: '文化' }],
          },
          {
            id: 'g7a-u5-w28',
            word: 'corn silk',
            senses: [{ pos: '', meaning: '玉米须' }],
            isPhrase: true,
          },
          {
            id: 'g7a-u5-w29',
            word: 'health',
            phonetic: '/hel0/',
            senses: [{ pos: 'n.', meaning: '健康(状况)' }],
          },
          {
            id: 'g7a-u5-w30',
            word: 'rose',
            phonetic: '/rəuz/',
            senses: [{ pos: 'n.', meaning: '玫瑰;蔷薇' }],
          },
          {
            id: 'g7a-u5-w31',
            word: 'cotton',
            phonetic: '/kotn/',
            senses: [{ pos: 'n.', meaning: '棉花' }],
          },
          {
            id: 'g7a-u5-w32',
            word: 'bamboo',
            phonetic: '/bæm\'bu:/',
            senses: [{ pos: 'n.', meaning: '竹,竹子' }],
          },
          {
            id: 'g7a-u5-w33',
            word: 'popular',
            phonetic: '/\'popjele/',
            senses: [{ pos: 'adj.', meaning: '受大众喜爱的,受欢迎的' }],
          },
          {
            id: 'g7a-u5-w34',
            word: 'key',
            phonetic: '/ki:/',
            senses: [{ pos: 'adj.', meaning: '至关重要的;必不可少的' }],
          },
          {
            id: 'g7a-u5-w35',
            word: 'news',
            phonetic: '/nju:z/',
            senses: [{ pos: 'n.', meaning: '消息' }],
          },
          {
            id: 'g7a-u5-w36',
            word: 'prefer',
            phonetic: '/pri\'f3:/',
            senses: [{ pos: 'v.', meaning: '更喜欢' }],
          },
          {
            id: 'g7a-u5-w37',
            word: 'coffee',
            phonetic: '/\'kofi/',
            senses: [{ pos: 'n.', meaning: '咖啡' }],
          },
          {
            id: 'g7a-u5-w38',
            word: 'secret',
            phonetic: '/si:krit/',
            senses: [{ pos: 'n.', meaning: '秘密' }],
          },
          {
            id: 'g7a-u5-w39',
            word: 'husband',
            phonetic: '/\'hazbend/',
            senses: [{ pos: 'n.', meaning: '丈夫' }],
          },
          {
            id: 'g7a-u5-w40',
            word: 'adult',
            phonetic: '/ædalt/',
            senses: [{ pos: 'n.', meaning: '成人,成年人' }],
          },
          {
            id: 'g7a-u5-w41',
            word: 'weekend',
            phonetic: '/,wi:k\'end/',
            senses: [{ pos: 'n.', meaning: '周末' }],
          },
          {
            id: 'g7a-u5-w42',
            word: 'chat',
            phonetic: '/tfæt/',
            senses: [{ pos: 'v.', meaning: '闲聊,闲谈,聊天' }],
          },
          {
            id: 'g7a-u5-w43',
            word: 'relax',
            phonetic: '/ri\'læks/',
            senses: [{ pos: 'v.', meaning: '放松,休息' }],
          },
          {
            id: 'g7a-u5-w44',
            word: 'yard',
            phonetic: '/ja:d/',
            senses: [{ pos: 'n.', meaning: '庭院' }],
          },
          {
            id: 'g7a-u5-w45',
            word: 'biscuit',
            phonetic: '/\'biskit/',
            senses: [{ pos: 'n.', meaning: '饼干' }],
          },
          {
            id: 'g7a-u5-w46',
            word: 'connect',
            phonetic: '/ka\'nekt/',
            senses: [{ pos: 'v.', meaning: '沟通;连接' }],
          },
